"use client";
import { useEffect, useMemo, useState } from "react";

type Settings={siteName:string;siteUrl:string;description:string;adminEmail:string;supportEmail:string;timezone:string;dateFormat:string;timeFormat:string;language:string;maintenance:boolean;registration:boolean;emailNotifications:boolean;analytics:boolean;defaultStatus:string;defaultAuthor:string;adminPageSize:number;sitePageSize:number;maxUploadMb:number;allowedTypes:string;imageQuality:number;generateWebp:boolean;smtpHost:string;smtpPort:number;smtpUser:string;smtpPassword:string;smtpSecure:boolean;mailFromName:string;mailFromEmail:string;sessionHours:number;minPasswordLength:number;requireUppercase:boolean;requireNumber:boolean;maxLoginAttempts:number;twoFactorRequired:boolean;allowedDomains:string;webhookUrl:string;analyticsProvider:string;analyticsMeasurementId:string;searchProvider:string;integrationApiKey:string;backupSchedule:string;backupRetention:number;logRetention:number;debugMode:boolean;apiAccess:boolean};
const initial:Settings={siteName:"OP8 Operating Partner Value Creation Framework",siteUrl:"https://op8framework.com",description:"OP8, sistematik değer yaratma için geliştirilmiş Operating Partner Framework'üdür.",adminEmail:"admin@op8.com",supportEmail:"support@op8.com",timezone:"Europe/Istanbul",dateFormat:"dd.MM.yyyy",timeFormat:"24",language:"tr",maintenance:false,registration:true,emailNotifications:true,analytics:true,defaultStatus:"draft",defaultAuthor:"OP8 Admin",adminPageSize:20,sitePageSize:12,maxUploadMb:10,allowedTypes:"jpg, jpeg, png, gif, webp, svg, pdf, doc, docx, xls, xlsx, ppt, pptx, zip",imageQuality:85,generateWebp:true,smtpHost:"",smtpPort:587,smtpUser:"",smtpPassword:"",smtpSecure:true,mailFromName:"OP8",mailFromEmail:"",sessionHours:168,minPasswordLength:10,requireUppercase:true,requireNumber:true,maxLoginAttempts:5,twoFactorRequired:false,allowedDomains:"",webhookUrl:"",analyticsProvider:"internal",analyticsMeasurementId:"",searchProvider:"internal",integrationApiKey:"",backupSchedule:"weekly",backupRetention:14,logRetention:90,debugMode:false,apiAccess:true};
const sections=[["general","⚙","Genel"],["branding","◩","Marka ve Tema"],["email","✉","E-posta"],["auth","♙","Kimlik Doğrulama"],["roles","♧","Roller ve Yetkiler"],["security","♢","Güvenlik"],["content","▤","İçerik Varsayılanları"],["media","▧","Medya Ayarları"],["seo","◇","SEO Yapılandırması"],["analytics","▥","Analitik Yapılandırması"],["integrations","⌘","Entegrasyonlar"],["backup","⇩","Veri Aktarma ve Yedekleme"],["status","◴","Sistem Durumu"],["logs","▧","Denetim Kayıtları"],["advanced","⚙","Gelişmiş"]];
export default function SettingsManager({preview=false}:{preview?:boolean}){const[value,setValue]=useState(initial),[section,setSection]=useState("general"),[query,setQuery]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[system,setSystem]=useState({posts:0,users:0,storage:0,updatedAt:null as string|null}),[logs,setLogs]=useState<{id:number;description:string;actorEmail:string;createdAt:string}[]>([]);
 useEffect(()=>{if(preview)return;fetch("/api/admin/settings",{cache:"no-store"}).then(r=>r.json()).then(data=>{if(data.item)setValue(data.item);if(data.system)setSystem(data.system);if(data.logs)setLogs(data.logs)})},[preview]);
 const shown=useMemo(()=>sections.filter(item=>item[2].toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR"))),[query]);
 const set=<K extends keyof Settings>(key:K,next:Settings[K])=>setValue(current=>({...current,[key]:next}));
 async function save(){setSaving(true);if(preview){await new Promise(r=>setTimeout(r,250));setMessage("Ayarlar önizleme modunda kaydedildi.");setSaving(false);return}const response=await fetch("/api/admin/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(value)});setMessage(response.ok?"Ayarlar başarıyla kaydedildi.":"Ayarlar kaydedilemedi.");setSaving(false)}
 async function action(name:string,payload:Record<string,unknown>={}){if(preview){setMessage(name==="clear-cache"?"Uygulama önbelleği temizlendi.":"Yapılandırma testi başarıyla tamamlandı.");return}const response=await fetch("/api/admin/settings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:name,...payload})}),data=await response.json();setMessage(data.message||data.error)}
 function downloadBackup(){const link=document.createElement("a");link.href="/api/admin/settings?action=backup";link.download="op8-backup.json";link.click();setMessage("Yedek dosyası hazırlanıyor.")}
 const storageGb=system.storage/1024/1024/1024,storagePercent=Math.min(100,Math.round(storageGb/50*100));
 return <section className="settings-page"><header className="settings-head"><div><h1>Ayarlar</h1><p>Sistem tercihlerini, yapılandırmayı ve entegrasyonları yönetin.</p></div><div><input placeholder="Ayarlarda ara..." value={query} onChange={e=>setQuery(e.target.value)}/><button className="settings-primary" onClick={()=>action("clear-cache")}>♙ Önbelleği Temizle</button><span className="health">Sistem Durumu <b>● Sağlıklı</b></span></div></header>{message&&<button className="settings-toast" onClick={()=>setMessage("")}>{message} ×</button>}
 <div className="settings-layout"><aside className="settings-menu"><h2>AYARLAR</h2>{shown.map(([key,icon,label])=><button key={key} className={section===key?"active":""} onClick={()=>setSection(key)}><i>{icon}</i>{label}</button>)}<div className="settings-help"><b>YARDIMA MI İHTİYACINIZ VAR?</b><p>Ayrıntılı kılavuzlar ve en iyi uygulamalar için dokümantasyonu inceleyin.</p><button onClick={()=>setMessage("Dokümantasyon merkezi yakında eklenecek.")}>Dokümantasyonu Gör</button></div></aside>
 <div className="settings-content"><section className="settings-form"><header><div><h2>{sections.find(x=>x[0]===section)?.[2]||"Genel Ayarlar"}</h2><p>OP8 platformunun temel yapılandırmasını yönetin.</p></div><button className="settings-primary" disabled={saving} onClick={save}>{saving?"Kaydediliyor…":"Değişiklikleri Kaydet"}</button></header>{section==="general"?<General value={value} set={set}/>:<SectionContent section={section} value={value} set={set} action={action} logs={logs} backup={downloadBackup}/>}</section></div>
 <aside className="settings-side"><section><h2>Sistem Bilgisi</h2>{[["Sürüm","v2.3.0"],["Ortam",preview?"Yerel Önizleme":"Production"],["Veritabanı","MySQL 8+"],["Çalışma Ortamı","Node.js"],["İçerik",String(system.posts)],["Kullanıcı",String(system.users)],["Son Güncelleme",system.updatedAt?new Date(system.updatedAt).toLocaleString("tr-TR"):"—"]].map(([a,b])=><p key={a}><span>{a}</span><b>{b}</b></p>)}</section><section><h2>Depolama Kullanımı</h2><div className="storage"><i style={{"--storage":`${storagePercent*3.6}deg`} as React.CSSProperties}/><strong>{storagePercent}%<small>50 GB alanın</small></strong></div><p><span>Kullanılan</span><b>{storageGb.toFixed(2)} GB</b></p><p><span>Kullanılabilir</span><b>{(50-storageGb).toFixed(2)} GB</b></p></section><section><h2>Hızlı İşlemler</h2>{[["clear-cache","Önbelleği temizle","Performansı iyileştir"],["reindex","Arama dizinini yenile","İçerik aramasını güncelle"],["optimize","Veritabanını kontrol et","Bakım denetimini çalıştır"],["logs","Sistem kayıtlarını görüntüle","Son etkinlikleri kontrol et"]].map(([key,title,desc])=><button className="quick" key={key} onClick={()=>key==="logs"?setSection("logs"):action(key)}><i>⚙</i><span><b>{title}</b><small>{desc}</small></span>›</button>)}</section></aside></div></section>}

function General({value,set}:{value:Settings;set:<K extends keyof Settings>(key:K,value:Settings[K])=>void}){return <div className="fields"><label>Site adı<input value={value.siteName} onChange={e=>set("siteName",e.target.value)}/></label><label>Site URL<input type="url" value={value.siteUrl} onChange={e=>set("siteUrl",e.target.value)}/></label><label className="wide">Site açıklaması<textarea rows={4} value={value.description} onChange={e=>set("description",e.target.value)}/></label><label>Yönetici e-postası<input type="email" value={value.adminEmail} onChange={e=>set("adminEmail",e.target.value)}/></label><label>Destek e-postası<input type="email" value={value.supportEmail} onChange={e=>set("supportEmail",e.target.value)}/></label><label>Saat dilimi<select value={value.timezone} onChange={e=>set("timezone",e.target.value)}><option value="Europe/Istanbul">(UTC+03:00) İstanbul</option><option value="UTC">UTC</option></select></label><label>Tarih biçimi<select value={value.dateFormat} onChange={e=>set("dateFormat",e.target.value)}><option value="dd.MM.yyyy">27.05.2026</option><option value="yyyy-MM-dd">2026-05-27</option></select></label><label>Saat biçimi<select value={value.timeFormat} onChange={e=>set("timeFormat",e.target.value)}><option value="24">24 Saat</option><option value="12">12 Saat (AM/PM)</option></select></label><label>Dil<select value={value.language} onChange={e=>set("language",e.target.value)}><option value="tr">Türkçe</option><option value="en">English</option></select></label><div className="wide toggles"><Toggle label="Bakım Modu" hint="Yalnızca yöneticiler erişebilir." value={value.maintenance} onChange={v=>set("maintenance",v)}/><Toggle label="Kullanıcı Kaydı" hint="Yeni kullanıcıların kayıt olmasına izin ver." value={value.registration} onChange={v=>set("registration",v)}/><Toggle label="E-posta Bildirimleri" hint="Sistem e-posta bildirimlerini gönder." value={value.emailNotifications} onChange={v=>set("emailNotifications",v)}/><Toggle label="Kullanım Analitiği" hint="Anonim kullanım ölçümüne izin ver." value={value.analytics} onChange={v=>set("analytics",v)}/></div></div>}
function SectionContent({section,value,set,action,logs,backup}:{section:string;value:Settings;set:<K extends keyof Settings>(key:K,value:Settings[K])=>void;action:(name:string,payload?:Record<string,unknown>)=>void;logs:{id:number;description:string;actorEmail:string;createdAt:string}[];backup:()=>void}){
 if(section==="content")return <ContentSettings value={value} set={set}/>;
 if(section==="media")return <MediaSettings value={value} set={set}/>;
 if(section==="email")return <div className="fields"><label>SMTP sunucusu<input value={value.smtpHost} onChange={e=>set("smtpHost",e.target.value)} placeholder="smtp.example.com"/></label><label>SMTP portu<input type="number" value={value.smtpPort} onChange={e=>set("smtpPort",Number(e.target.value))}/></label><label>SMTP kullanıcısı<input value={value.smtpUser} onChange={e=>set("smtpUser",e.target.value)}/></label><label>SMTP parolası<input type="password" value={value.smtpPassword} onChange={e=>set("smtpPassword",e.target.value)}/></label><label>Gönderici adı<input value={value.mailFromName} onChange={e=>set("mailFromName",e.target.value)}/></label><label>Gönderici e-postası<input type="email" value={value.mailFromEmail} onChange={e=>set("mailFromEmail",e.target.value)}/></label><div className="wide"><Toggle label="Güvenli SMTP" hint="TLS ile güvenli bağlantı kullan." value={value.smtpSecure} onChange={v=>set("smtpSecure",v)}/><button onClick={()=>action("test-email",{smtpHost:value.smtpHost,mailFromEmail:value.mailFromEmail})}>E-posta yapılandırmasını test et</button></div></div>;
 if(section==="auth"||section==="security")return <div className="fields"><label>Oturum süresi (saat)<input type="number" min="1" value={value.sessionHours} onChange={e=>set("sessionHours",Number(e.target.value))}/></label><label>Asgari parola uzunluğu<input type="number" min="8" max="64" value={value.minPasswordLength} onChange={e=>set("minPasswordLength",Number(e.target.value))}/></label><label>Azami başarısız giriş<input type="number" min="3" max="20" value={value.maxLoginAttempts} onChange={e=>set("maxLoginAttempts",Number(e.target.value))}/></label><label>İzin verilen e-posta alan adları<input value={value.allowedDomains} onChange={e=>set("allowedDomains",e.target.value)} placeholder="op8.com, şirket.com"/></label><div className="wide toggles"><Toggle label="Büyük harf zorunlu" hint="Parolada en az bir büyük harf iste." value={value.requireUppercase} onChange={v=>set("requireUppercase",v)}/><Toggle label="Rakam zorunlu" hint="Parolada en az bir rakam iste." value={value.requireNumber} onChange={v=>set("requireNumber",v)}/><Toggle label="İki aşamalı doğrulama" hint="Yönetici hesaplarında 2FA zorunlu olsun." value={value.twoFactorRequired} onChange={v=>set("twoFactorRequired",v)}/></div></div>;
 if(section==="integrations")return <div className="fields"><label>Analitik sağlayıcısı<select value={value.analyticsProvider} onChange={e=>set("analyticsProvider",e.target.value)}><option value="internal">OP8 Dahili Analitik</option><option value="ga4">Google Analytics 4</option><option value="posthog">PostHog</option></select></label><label>Ölçüm kimliği<input value={value.analyticsMeasurementId} onChange={e=>set("analyticsMeasurementId",e.target.value)}/></label><label>Arama sağlayıcısı<select value={value.searchProvider} onChange={e=>set("searchProvider",e.target.value)}><option value="internal">Dahili arama</option><option value="algolia">Algolia</option></select></label><label>API anahtarı<input type="password" value={value.integrationApiKey} onChange={e=>set("integrationApiKey",e.target.value)}/></label><label className="wide">Webhook URL<input type="url" value={value.webhookUrl} onChange={e=>set("webhookUrl",e.target.value)}/></label><button onClick={()=>action("test-integration",{webhookUrl:value.webhookUrl,analyticsMeasurementId:value.analyticsMeasurementId})}>Entegrasyonu test et</button></div>;
 if(section==="backup")return <div className="fields"><label>Otomatik yedekleme<select value={value.backupSchedule} onChange={e=>set("backupSchedule",e.target.value)}><option value="daily">Her gün</option><option value="weekly">Her hafta</option><option value="monthly">Her ay</option><option value="off">Kapalı</option></select></label><label>Saklama süresi (gün)<input type="number" min="1" max="365" value={value.backupRetention} onChange={e=>set("backupRetention",Number(e.target.value))}/></label><div className="wide backup-actions"><button className="settings-primary" onClick={backup}>JSON yedeğini indir</button><p>Yedek; ayarları, içerikleri ve hassas olmayan kullanıcı alanlarını içerir. Parolalar ve API anahtarları dışa aktarılmaz.</p></div></div>;
 if(section==="logs")return <div className="settings-logs">{logs.length?logs.map(log=><article key={log.id}><i>◷</i><span><b>{log.description}</b><small>{log.actorEmail} · {new Date(log.createdAt).toLocaleString("tr-TR")}</small></span></article>):<p>Henüz aktivite kaydı bulunmuyor.</p>}</div>;
 if(section==="advanced")return <div className="fields"><label>Kayıt saklama süresi (gün)<input type="number" min="7" max="730" value={value.logRetention} onChange={e=>set("logRetention",Number(e.target.value))}/></label><div/><div className="wide toggles"><Toggle label="API erişimi" hint="Harici istemcilerin yetkili API erişimine izin ver." value={value.apiAccess} onChange={v=>set("apiAccess",v)}/><Toggle label="Hata ayıklama modu" hint="Yalnızca yerel testlerde ayrıntılı hata kaydı üret." value={value.debugMode} onChange={v=>set("debugMode",v)}/></div></div>;
 if(section==="analytics")return <div className="toggles"><Toggle label="Kullanım analitiği" hint="Anonim ziyaret ve performans verilerini kaydet." value={value.analytics} onChange={v=>set("analytics",v)}/></div>;
 if(section==="branding")return <ModuleLink href="/admin/tema" title="Marka ve Tema yöneticisini aç" text="Renk paleti ve tipografi ayarlarını gerçek tema modülünde yönetin."/>;
 if(section==="roles")return <ModuleLink href="/admin/kullanicilar" title="Kullanıcı ve rol yönetimini aç" text="Rolleri gerçek kullanıcı hesaplarına atayın ve erişim durumlarını yönetin."/>;
 if(section==="seo")return <ModuleLink href="/admin/seo" title="SEO modülünü aç" text="Site geneli SEO, içerik puanları ve denetim sonuçlarını yönetin."/>;
 if(section==="status")return <div className="section-note"><article><i>●</i><div><h3>Sistem sağlığı</h3><p>Sayfa, API ve veritabanı erişimi sistem bilgileri üzerinden doğrulanıyor.</p></div></article></div>;
 return <div className="section-note"><article><i>⚙</i><div><h3>Ayar grubu</h3><p>Bu ayar grubu kullanıma hazırdır.</p></div></article></div>}
function ModuleLink({href,title,text}:{href:string;title:string;text:string}){return <div className="section-note"><article><i>↗</i><div><h3>{title}</h3><p>{text}</p><a href={href} target="_top">Modüle git</a></div></article></div>}
function ContentSettings({value,set}:{value:Settings;set:<K extends keyof Settings>(key:K,value:Settings[K])=>void}){return <section className="settings-small"><h2>Varsayılan İçerik Ayarları</h2><label>Yeni içerik durumu<select value={value.defaultStatus} onChange={e=>set("defaultStatus",e.target.value)}><option value="draft">Taslak</option><option value="review">İncelemede</option></select></label><label>Varsayılan yazar<input value={value.defaultAuthor} onChange={e=>set("defaultAuthor",e.target.value)}/></label><label>Yönetimde sayfa başına<input type="number" min="5" max="100" value={value.adminPageSize} onChange={e=>set("adminPageSize",Number(e.target.value))}/></label><label>Sitede sayfa başına<input type="number" min="3" max="50" value={value.sitePageSize} onChange={e=>set("sitePageSize",Number(e.target.value))}/></label></section>}
function MediaSettings({value,set}:{value:Settings;set:<K extends keyof Settings>(key:K,value:Settings[K])=>void}){return <section className="settings-small"><h2>Medya Ayarları</h2><label>Azami dosya boyutu<select value={value.maxUploadMb} onChange={e=>set("maxUploadMb",Number(e.target.value))}><option value="5">5 MB</option><option value="10">10 MB</option><option value="25">25 MB</option></select></label><label>İzin verilen türler<input value={value.allowedTypes} onChange={e=>set("allowedTypes",e.target.value)}/></label><label>Görsel kalitesi<input type="number" min="40" max="100" value={value.imageQuality} onChange={e=>set("imageQuality",Number(e.target.value))}/></label><Toggle label="WebP görselleri üret" hint="Yüklenen görsellerin WebP sürümünü hazırla." value={value.generateWebp} onChange={v=>set("generateWebp",v)}/></section>}
function Toggle({label,hint,value,onChange}:{label:string;hint:string;value:boolean;onChange:(value:boolean)=>void}){return <label className="toggle"><span><b>{label}</b><small>{hint}</small></span><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/><i/></label>}
