Exit code: 0
Wall time: 2.8 seconds
Output:
"use client";import{FormEvent,useEffect,useState}from"react";
type Category={id:number;name:string;slug:string;description:string;color:string;sortOrder:number;postCount:number};type Post={id:number;title:string;slug:string;status:string;categoryId:number|null};
const blank={name:"",slug:"",description:"",color:"#ee7551"};
export default function CategoryManager(){const[categories,setCategories]=useState<Category[]>([]);const[posts,setPosts]=useState<Post[]>([]);const[form,setForm]=useState(blank);const[editing,setEditing]=useState<Category|null>(null);const[busy,setBusy]=useState(true);const[message,setMessage]=useState("");
async function load(){setBusy(true);const r=await fetch("/api/admin/categories");const d=await r.json();if(r.ok){setCategories(d.categories);setPosts(d.posts)}else setMessage(d.error);setBusy(false)}useEffect(()=>{load()},[]);
async function submit(e:FormEvent){e.preventDefault();setMessage("");const r=await fetch("/api/admin/categories",{method:editing?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(editing?{...form,id:editing.id}:form)});const d=await r.json();if(!r.ok){setMessage(d.error);return}setForm(blank);setEditing(null);setMessage(editing?"Kategori güncellendi.":"Kategori eklendi.");await load()}
function edit(c:Category){setEditing(c);setForm({name:c.name,slug:c.slug,description:c.description,color:c.color});window.scrollTo({top:0,behavior:"smooth"})}
async function remove(c:Category){if(!confirm(`“${c.name}” kategorisi silinsin mi? Bağlı yazılar kategorisiz kalacak.`))return;await fetch("/api/admin/categories",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:c.id})});setMessage("Kategori silindi.");await load()}
async function move(index:number,delta:number){const target=index+delta;if(target<0||target>=categories.length)return;const next=[...categories];[next[index],next[target]]=[next[target],next[index]];setCategories(next);await fetch("/api/admin/categories",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({order:next.map(c=>c.id)})})}
async function assign(postId:number,value:string){await fetch("/api/admin/categories",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({postId,categoryId:value?Number(value):null})});setPosts(ps=>ps.map(p=>p.id===postId?{...p,categoryId:value?Number(value):null}:p));setMessage("Yazı kategorisi güncellendi.")}
return <div className="category-admin"><div className="admin-title"><div><p className="eyebrow">İÇERİK YÖNETİMİ</p><h1>Kategoriler</h1><p>Konu yapısını düzenle, sırasını belirle ve yazıları kategorilere bağla.</p></div><span>{categories.length} kategori</span></div>{message&&<p className="admin-message" role="status">{message}</p>}<div className="admin-grid"><form className="category-form" onSubmit={submit}><div className="form-head"><h2>{editing?"Kategoriyi düzenle":"Yeni kategori"}</h2>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(blank)}}>Vazgeç</button>}</div><label>Ad<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Örn. Tasarım"/></label><label>Slug<input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} placeholder="Boşsa otomatik oluşur"/><small>URL’de kullanılacak kısa ve benzersiz ad.</small></label><label>Açıklama<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Renk<input type="color" value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></label><button className="admin-primary" type="submit">{editing?"Değişiklikleri kaydet":"Kategori ekle"}</button></form><section className="category-list"><div className="list-head"><h2>Kategori sırası</h2><span>Oklarla sırala</span></div>{busy?<p>Yükleniyor…</p>:categories.map((c,i)=><article className="category-row" key={c.id}><span className="category-color" style={{background:c.color}}/><div><h3>{c.name}</h3><code>/{c.slug}</code><p>{c.description||"Açıklama yok"}</p></div><span className="post-count">{c.postCount} yazı</span><div className="order-buttons"><button onClick={()=>move(i,-1)} disabled={i===0} aria-label={`${c.name} yukarı taşı`}>↑</button><button onClick={()=>move(i,1)} disabled={i===categories.length-1} aria-label={`${c.name} aşağı taşı`}>↓</button></div><div className="row-actions"><button onClick={()=>edit(c)}>Düzenle</button><button className="danger" onClick={()=>remove(c)}>Sil</button></div></article>)}</section></div><section className="post-assignment"><div className="list-head"><div><p className="kicker">YAZI BAĞLANTILARI</p><h2>Yazıları kategorilere bağla</h2></div><span>{posts.length} yazı</span></div>{posts.map(p=><div className="post-assign-row" key={p.id}><div><h3>{p.title}</h3><span>{p.status==="published"?"Yayında":"Taslak"} · /{p.slug}</span></div><label><span className="sr-only">Kategori seç</span><select value={p.categoryId??""} onChange={e=>assign(p.id,e.target.value)}><option value="">Kategorisiz</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label></div>)}</section></div>}

