"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
type Category={id:number;name:string;slug:string;description:string;color:string;sortOrder:number;postCount:number};
type Post={id:number;title:string;slug:string;status:string;categoryId:number|null};
const blank={name:"",slug:"",description:"",color:"#0872ed"};
const engines=["Growth","Sales","Delivery","Operations","People","Profitability","Portfolio","Customer Success"];
const previewCategories:Category[]=[
 {id:1,name:"OP8™ Framework",slug:"op8-framework",description:"Ana framework ve değer yaratma metodolojisi.",color:"#0872ed",sortOrder:1,postCount:8},
 {id:2,name:"01. Growth",slug:"growth",description:"Sürdürülebilir büyüme stratejileri ve uygulamaları.",color:"#2da95c",sortOrder:10,postCount:6},
 {id:3,name:"02. Sales",slug:"sales",description:"Satış mükemmelliği ve gelir motoru.",color:"#0872ed",sortOrder:20,postCount:5},
 {id:4,name:"03. Delivery",slug:"delivery",description:"Kalite, zaman ve kârlılıkla değer teslimi.",color:"#ff7818",sortOrder:30,postCount:4},
 {id:5,name:"04. Operations",slug:"operations",description:"Operasyonel verimlilik ve süreç mükemmelliği.",color:"#12a6ae",sortOrder:40,postCount:7},
 {id:6,name:"05. People",slug:"people",description:"İnsan, liderlik ve organizasyonel yetkinlik.",color:"#7844dd",sortOrder:50,postCount:3},
 {id:7,name:"06. Profitability",slug:"profitability",description:"Kârlılığı ve finansal performansı geliştirme.",color:"#36a95f",sortOrder:60,postCount:6},
 {id:8,name:"07. Portfolio",slug:"portfolio",description:"Portföy stratejisi ve kaynak tahsisi.",color:"#ffad00",sortOrder:70,postCount:0},
 {id:9,name:"08. Customer Success",slug:"customer-success",description:"Müşteri değeri, bağlılık ve büyüme.",color:"#f14f55",sortOrder:80,postCount:5}
];
const previewPosts:Post[]=[{id:1,title:"OP8 Framework Nedir?",slug:"op8-framework-nedir",status:"published",categoryId:1},{id:2,title:"Growth Strategy Best Practices",slug:"growth-strategy",status:"draft",categoryId:2},{id:3,title:"EBITDA Nasıl Geliştirilir?",slug:"ebitda-gelistirme",status:"published",categoryId:7}];
export default function CategoryManager({preview=false}:{preview?:boolean}){
 const[categories,setCategories]=useState<Category[]>(preview?previewCategories:[]),[posts,setPosts]=useState<Post[]>(preview?previewPosts:[]),[form,setForm]=useState(blank),[editing,setEditing]=useState<Category|null>(null),[busy,setBusy]=useState(!preview),[message,setMessage]=useState("");
 const[query,setQuery]=useState(""),[engine,setEngine]=useState("all"),[view,setView]=useState<"list"|"cards">("list"),[page,setPage]=useState(1),[size,setSize]=useState(10),[selected,setSelected]=useState<number[]>([]),[modal,setModal]=useState(false),[settings,setSettings]=useState(false);
 async function load(){if(preview)return;setBusy(true);const r=await fetch("/api/admin/categories"),d=await r.json();if(r.ok){setCategories(d.categories);setPosts(d.posts)}else setMessage(d.error);setBusy(false)}
 useEffect(()=>{if(!preview)load()},[preview]);
 const filtered=useMemo(()=>categories.filter(c=>(engine==="all"||c.name.toLowerCase().includes(engine.toLowerCase()))&&`${c.name} ${c.slug} ${c.description}`.toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR"))),[categories,query,engine]);
 const pages=Math.max(1,Math.ceil(filtered.length/size)),current=Math.min(page,pages),items=filtered.slice((current-1)*size,current*size);
 useEffect(()=>setPage(1),[query,engine,size]);
 function create(){setEditing(null);setForm(blank);setModal(true)}
 function edit(c:Category){setEditing(c);setForm({name:c.name,slug:c.slug,description:c.description,color:c.color});setModal(true)}
 async function submit(e:FormEvent){e.preventDefault();if(preview){if(editing)setCategories(cs=>cs.map(c=>c.id===editing.id?{...c,...form}:c));else setCategories(cs=>[...cs,{...form,id:Math.max(0,...cs.map(c=>c.id))+1,sortOrder:(cs.length+1)*10,postCount:0}]);setModal(false);setMessage(editing?"Kategori güncellendi (test).":"Kategori oluşturuldu (test).");return}const r=await fetch("/api/admin/categories",{method:editing?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,id:editing?.id})});const d=await r.json();if(!r.ok)return setMessage(d.error);setModal(false);setMessage(editing?"Kategori güncellendi.":"Kategori oluşturuldu.");await load()}
 async function remove(c:Category){if(!confirm(`“${c.name}” silinsin mi?`))return;if(preview){setCategories(cs=>cs.filter(x=>x.id!==c.id));setPosts(ps=>ps.map(p=>p.categoryId===c.id?{...p,categoryId:null}:p));setMessage("Kategori silindi (test).");return}await fetch("/api/admin/categories",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:c.id})});setMessage("Kategori silindi.");await load()}
 async function move(c:Category,dir:number){const at=categories.findIndex(x=>x.id===c.id),to=at+dir;if(to<0||to>=categories.length)return;const next=[...categories];[next[at],next[to]]=[next[to],next[at]];setCategories(next);if(!preview)await fetch("/api/admin/categories",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({order:next.map(x=>x.id)})});else setMessage("Kategori sırası değiştirildi (test).")}
 async function assign(postId:number,value:string){if(!preview)await fetch("/api/admin/categories",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({postId,categoryId:value?Number(value):null})});setPosts(ps=>ps.map(p=>p.id===postId?{...p,categoryId:value?Number(value):null}:p));setMessage(preview?"Yazı kategorisi güncellendi (test).":"Yazı kategorisi güncellendi.")}
 function bulkDelete(){if(!selected.length)return setMessage("Önce kategori seçin.");setMessage(`${selected.length} kategori seçildi. Silme işlemi her kategori için onay gerektirir.`)}
 const published=categories.filter(c=>c.postCount>0).length,totalContent=categories.reduce((n,c)=>n+c.postCount,0);
 return <div className="cat-admin">
  <header className="cat-head"><div><h1>Kategoriler</h1><p>İçeriklerinizi kategori ve alt kategorilerle düzenleyin.</p></div><div><label>⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Kategori ara..."/></label><button className="cat-primary" onClick={create}>＋ Kategori Oluştur</button><button onClick={()=>setMessage("CSV içe aktarma şablonu hazır.")}>⇩ İçe Aktar</button><button onClick={()=>setSettings(true)}>⚙ Kategori Ayarları</button></div></header>
  {message&&<p className="admin-message" role="status">{message}</p>}
  <section className="cat-stats">{[["Toplam Kategori",categories.length,"#0872ed"],["Yayında",published,"#2da95c"],["Taslak",categories.length-published,"#ffad00"],["Boş Kategori",categories.length-published,"#7844dd"],["Toplam İçerik",totalContent,"#12a6ae"]].map(([l,v,c])=><article style={{"--c":c} as React.CSSProperties} key={l}><i>▰</i><span><small>{l}</small><b>{v}</b><em>Genel durum</em></span></article>)}</section>
  <div className="cat-layout"><aside className="cat-tree"><h2>Kategori Hiyerarşisi　⌕</h2><b>⌄　▱ OP8™ Framework <span>{totalContent}</span></b>{categories.map(c=><button key={c.id} onClick={()=>edit(c)}>⌄　▱ {c.name}<span>{c.postCount}</span></button>)}<button className="tree-add" onClick={create}>＋ Ana Kategori Ekle</button></aside>
   <section className="cat-panel"><h2>Tüm Kategoriler</h2><div className="cat-toolbar"><select aria-label="Toplu işlem"><option>Toplu İşlemler</option><option>Yayına al</option><option>Taslağa al</option></select><button onClick={bulkDelete}>Uygula</button><select value={engine} onChange={e=>setEngine(e.target.value)}><option value="all">Tüm Motorlar</option>{engines.map(x=><option key={x}>{x}</option>)}</select><label>⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Kategori ara..."/></label><button className={view==="list"?"active":""} onClick={()=>setView("list")} aria-label="Liste görünümü">▦</button><button className={view==="cards"?"active":""} onClick={()=>setView("cards")} aria-label="Kart görünümü">▦</button></div>
   {view==="list"?<div className="cat-table-wrap"><table className="cat-table"><thead><tr><th><input type="checkbox" checked={selected.length===items.length&&items.length>0} onChange={e=>setSelected(e.target.checked?items.map(c=>c.id):[])}/></th><th></th><th>Kategori</th><th>Açıklama</th><th>Motor</th><th>İçerik</th><th>Durum</th><th>Sıra</th><th>İşlemler</th></tr></thead><tbody>{busy?<tr><td colSpan={9}>Yükleniyor…</td></tr>:items.map(c=><tr key={c.id}><td><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>setSelected(e.target.checked?[...selected,c.id]:selected.filter(x=>x!==c.id))}/></td><td>⠿</td><td><div className="cat-name"><i style={{background:c.color}}>▱</i><span><b>{c.name}</b><small>/{c.slug}</small></span></div></td><td>{c.description||"Açıklama yok"}</td><td><span className="cat-engine">{engines.find(x=>c.name.toLowerCase().includes(x.toLowerCase()))||"Value Creation"}</span></td><td>{c.postCount}</td><td><span className={`cat-status ${c.postCount?"published":"draft"}`}>{c.postCount?"Yayında":"Taslak"}</span></td><td><div className="cat-order">{c.sortOrder}<button onClick={()=>move(c,-1)}>↑</button><button onClick={()=>move(c,1)}>↓</button></div></td><td><div className="cat-actions"><button onClick={()=>edit(c)} aria-label={`${c.name} düzenle`}>✎</button><button onClick={create} aria-label="Alt kategori ekle">＋</button><button onClick={()=>remove(c)} aria-label={`${c.name} sil`}>⋮</button></div></td></tr>)}</tbody></table></div>:<div className="cat-cards">{items.map(c=><article style={{borderTopColor:c.color}} key={c.id}><span>{c.postCount} içerik</span><h3>{c.name}</h3><p>{c.description}</p><button onClick={()=>edit(c)}>Düzenle</button></article>)}</div>}
   <footer className="cat-pages"><span>{filtered.length?`${(current-1)*size+1}–${Math.min(current*size,filtered.length)} arası`:"0 sonuç"} · Toplam {filtered.length}</span><div><button disabled={current===1} onClick={()=>setPage(current-1)}>‹</button>{Array.from({length:pages},(_,i)=>i+1).map(n=><button className={n===current?"active":""} onClick={()=>setPage(n)} key={n}>{n}</button>)}<button disabled={current===pages} onClick={()=>setPage(current+1)}>›</button></div><label>Sayfa başına <select value={size} onChange={e=>setSize(Number(e.target.value))}><option>5</option><option>10</option><option>20</option></select></label></footer></section></div>
  <section className="cat-assign"><h2>Yazıları kategorilere bağla</h2>{posts.slice(0,10).map(p=><label key={p.id}><span><b>{p.title}</b><small>/{p.slug}</small></span><select value={p.categoryId??""} onChange={e=>assign(p.id,e.target.value)}><option value="">Kategorisiz</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label>)}</section>
  {modal&&<div className="editor-overlay" role="dialog"><form className="cat-modal" onSubmit={submit}><header><h2>{editing?"Kategoriyi düzenle":"Yeni kategori"}</h2><button type="button" onClick={()=>setModal(false)}>×</button></header><label>Kategori adı<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Slug<input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label><label>Açıklama<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Renk<input type="color" value={form.color} onChange={e=>setForm({...form,color:e.target.value})}/></label><div><button type="button" onClick={()=>setModal(false)}>Vazgeç</button><button className="cat-primary">Kaydet</button></div></form></div>}
  {settings&&<div className="editor-overlay" role="dialog"><section className="cat-modal"><header><h2>Kategori ayarları</h2><button onClick={()=>setSettings(false)}>×</button></header><label>Varsayılan görünüm<select value={view} onChange={e=>setView(e.target.value as "list"|"cards")}><option value="list">Liste</option><option value="cards">Kartlar</option></select></label><label>Sayfa başına<select value={size} onChange={e=>setSize(Number(e.target.value))}><option>5</option><option>10</option><option>20</option></select></label><button className="cat-primary" onClick={()=>{setSettings(false);setMessage("Kategori ayarları kaydedildi.")}}>Ayarları kaydet</button></section></div>}
 </div>
}
