import{asc,eq,sql}from"drizzle-orm";import{getDb}from"../../../../db";import{categories,posts}from"../../../../db/schema";import{getChatGPTUser}from"../../../chatgpt-auth";
const colors=["#ee7551","#9ab8a6","#b7a4bd","#d8ae8f","#7f9ca5"];
type LocalCategory={id:number;name:string;slug:string;description:string;color:string;sortOrder:number;postCount:number};type LocalPost={id:number;title:string;slug:string;status:string;categoryId:number|null};
const localState:{categories:LocalCategory[];posts:LocalPost[]}={categories:[{id:1,name:"Üretkenlik",slug:"uretkenlik",description:"Daha iyi çalışma ve düşünme sistemleri",color:colors[0],sortOrder:0,postCount:2},{id:2,name:"Teknoloji",slug:"teknoloji",description:"Araçlar, ürünler ve yeni davranışlar",color:colors[1],sortOrder:1,postCount:1},{id:3,name:"Dijital Kültür",slug:"dijital-kultur",description:"Ekranlarla değişen gündelik hayat",color:colors[2],sortOrder:2,postCount:1},{id:4,name:"Notlar",slug:"notlar",description:"Kısa gözlemler ve fikirler",color:colors[3],sortOrder:3,postCount:0}],posts:[{id:1,title:"Dijital sadelik: Daha azıyla daha iyi düşünmek",slug:"dijital-sadelik",status:"published",categoryId:1},{id:2,title:"Daha az araçla daha iyi bir çalışma sistemi kurmak",slug:"daha-az-aracla-calisma-sistemi",status:"published",categoryId:1},{id:3,title:"Yapay zekâyı günlük işe gerçekten dahil etmek",slug:"yapay-zekayi-gunluk-ise-dahil-etmek",status:"published",categoryId:2},{id:4,title:"Bildirimlerden sonra: Dikkatin yeni ekonomisi",slug:"dikkatin-yeni-ekonomisi",status:"published",categoryId:3}]};
const isLocal=()=>process.env.LOCAL_TEST_MODE==="1";function recount(){for(const c of localState.categories)c.postCount=localState.posts.filter(p=>p.categoryId===c.id).length}
function slugify(value:string){return value.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"i").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,64)}
async function auth(){return Boolean(await getChatGPTUser())}
async function seed(){const db=getDb();const [{count}]=await db.select({count:sql<number>`count(*)`}).from(categories);if(Number(count)===0){await db.insert(categories).values([{name:"Üretkenlik",slug:"uretkenlik",description:"Daha iyi çalışma ve düşünme sistemleri",color:colors[0],sortOrder:0},{name:"Teknoloji",slug:"teknoloji",description:"Araçlar, ürünler ve yeni davranışlar",color:colors[1],sortOrder:1},{name:"Dijital Kültür",slug:"dijital-kultur",description:"Ekranlarla değişen gündelik hayat",color:colors[2],sortOrder:2},{name:"Notlar",slug:"notlar",description:"Kısa gözlemler ve fikirler",color:colors[3],sortOrder:3}]);const rows=await db.select().from(categories).orderBy(asc(categories.sortOrder));await db.insert(posts).values([{title:"Dijital sadelik: Daha azıyla daha iyi düşünmek",slug:"dijital-sadelik",status:"published",categoryId:rows[0].id},{title:"Daha az araçla daha iyi bir çalışma sistemi kurmak",slug:"daha-az-aracla-calisma-sistemi",status:"published",categoryId:rows[0].id},{title:"Yapay zekâyı günlük işe gerçekten dahil etmek",slug:"yapay-zekayi-gunluk-ise-dahil-etmek",status:"published",categoryId:rows[1].id},{title:"Bildirimlerden sonra: Dikkatin yeni ekonomisi",slug:"dikkatin-yeni-ekonomisi",status:"published",categoryId:rows[2].id}])}}
export async function GET(){if(!await auth())return Response.json({error:"Yetkisiz"},{status:401});await seed();const db=getDb();const list=await db.select({id:categories.id,name:categories.name,slug:categories.slug,description:categories.description,color:categories.color,sortOrder:categories.sortOrder,postCount:sql<number>`count(${posts.id})`}).from(categories).leftJoin(posts,eq(posts.categoryId,categories.id)).groupBy(categories.id).orderBy(asc(categories.sortOrder),asc(categories.name));const allPosts=await db.select().from(posts).orderBy(asc(posts.title));return Response.json({categories:list,posts:allPosts})}
export async function POST(request:Request){if(!await auth())return Response.json({error:"Yetkisiz"},{status:401});const input=await request.json()as{name?:string;slug?:string;description?:string;color?:string};const name=input.name?.trim()??"";const slug=slugify(input.slug?.trim()||name);if(!name||!slug)return Response.json({error:"Ad ve geçerli slug zorunludur."},{status:400});try{const db=getDb();const [{max}]=await db.select({max:sql<number>`coalesce(max(${categories.sortOrder}), -1)`}).from(categories);const [created]=await db.insert(categories).values({name,slug,description:input.description?.trim()??"",color:input.color??colors[0],sortOrder:Number(max)+1,updatedAt:new Date().toISOString()}).returning();return Response.json({category:created},{status:201})}catch{return Response.json({error:"Bu slug zaten kullanılıyor."},{status:409})}}
export async function PUT(request:Request){if(!await auth())return Response.json({error:"Yetkisiz"},{status:401});const input=await request.json()as{id?:number;name?:string;slug?:string;description?:string;color?:string};const id=Number(input.id);const name=input.name?.trim()??"";const slug=slugify(input.slug?.trim()||name);if(!id||!name||!slug)return Response.json({error:"Eksik alan var."},{status:400});try{const [updated]=await getDb().update(categories).set({name,slug,description:input.description?.trim()??"",color:input.color??colors[0],updatedAt:new Date().toISOString()}).where(eq(categories.id,id)).returning();return Response.json({category:updated})}catch{return Response.json({error:"Bu slug zaten kullanılıyor."},{status:409})}}
export async function PATCH(request:Request){if(!await auth())return Response.json({error:"Yetkisiz"},{status:401});const input=await request.json()as{order?:number[];postId?:number;categoryId?:number|null};const db=getDb();if(Array.isArray(input.order)){await db.batch(input.order.map((id,index)=>db.update(categories).set({sortOrder:index,updatedAt:new Date().toISOString()}).where(eq(categories.id,id))));return Response.json({ok:true})}if(input.postId){await db.update(posts).set({categoryId:input.categoryId??null}).where(eq(posts.id,input.postId));return Response.json({ok:true})}return Response.json({error:"Geçersiz işlem"},{status:400})}
export async function DELETE(request:Request){if(!await auth())return Response.json({error:"Yetkisiz"},{status:401});const{id}=await request.json()as{id?:number};if(!id)return Response.json({error:"Kategori bulunamadı"},{status:400});const db=getDb();await db.batch([db.update(posts).set({categoryId:null}).where(eq(posts.categoryId,id)),db.delete(categories).where(eq(categories.id,id))]);return Response.json({ok:true})}
