"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";

type User = { id:number; email:string; displayName:string; role:string; team:string; status:string; lastLoginAt:string|null; createdAt:string };
type Invite = { id:number; email:string; displayName:string; role:string; team:string; createdAt:string };
type Activity = { id:number; description:string; createdAt:string };
type FormState = { displayName:string; email:string; role:string; team:string; status:string };

const roles: Record<string,string> = { super_admin:"Süper Yönetici", admin:"Yönetici", editor:"Editör", author:"Yazar", member:"Site Üyesi" };
const blank: FormState = { displayName:"", email:"", role:"member", team:"Genel", status:"active" };
const samples: User[] = [
  [1,"John Doe","john.doe@op8.com","admin","Yönetim"], [2,"Sarah Miller","sarah.miller@op8.com","editor","İçerik ve Araştırma"],
  [3,"Michael Brown","michael.brown@op8.com","editor","Büyüme ve SEO"], [4,"Emily Johnson","emily.johnson@op8.com","member","Analitik"],
  [5,"David Wilson","david.wilson@op8.com","author","Pazarlama"], [6,"Lisa Anderson","lisa.anderson@op8.com","editor","İçerik ve Araştırma"],
  [7,"James Taylor","james.taylor@op8.com","member","Leads ve CRM"], [8,"Robert Martinez","robert.martinez@op8.com","super_admin","Yönetim"]
].map(([id,displayName,email,role,team],index)=>({ id:id as number, displayName:displayName as string, email:email as string, role:role as string, team:team as string, status:index===6?"disabled":"active", lastLoginAt:new Date(Date.now()-index*86400000).toISOString(), createdAt:new Date(2026,0,15+index*5).toISOString() }));

export default function UserManager({ preview=false }:{ preview?:boolean }) {
  const [users,setUsers]=useState<User[]>(preview?samples:[]), [invites,setInvites]=useState<Invite[]>(preview?[{id:1,email:"alex.white@op8.com",displayName:"Alex White",role:"editor",team:"İçerik",createdAt:new Date().toISOString()}]:[]);
  const [activities,setActivities]=useState<Activity[]>([]), [query,setQuery]=useState(""), [role,setRole]=useState("all"), [status,setStatus]=useState("all"), [team,setTeam]=useState("all"), [tab,setTab]=useState("all"), [page,setPage]=useState(1), [size,setSize]=useState(10), [grid,setGrid]=useState(false), [modal,setModal]=useState(false), [editing,setEditing]=useState<number|null>(null), [form,setForm]=useState<FormState>(blank), [message,setMessage]=useState("");
  const importRef=useRef<HTMLInputElement>(null);
  async function load(){ if(preview)return; const response=await fetch("/api/admin/users",{cache:"no-store"}); if(response.ok){const data=await response.json(); setUsers(data.items||[]);setInvites(data.invites||[]);setActivities(data.activities||[])} }
  useEffect(()=>{void load()},[]);
  useEffect(()=>setPage(1),[query,role,status,team,tab,size]);
  const filtered=useMemo(()=>users.filter(user=>{
    const tabOk=tab==="all"||(tab==="admins"&&["super_admin","admin"].includes(user.role))||(tab==="editors"&&user.role==="editor")||(tab==="members"&&["author","member"].includes(user.role))||(tab==="disabled"&&user.status==="disabled");
    return tabOk&&(role==="all"||user.role===role)&&(status==="all"||user.status===status)&&(team==="all"||user.team===team)&&`${user.displayName} ${user.email}`.toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR"));
  }),[users,query,role,status,team,tab]);
  const totalPages=Math.max(1,Math.ceil(filtered.length/size)), pageUsers=filtered.slice((page-1)*size,page*size);
  function openEditor(user?:User){setEditing(user?.id||null);setForm(user?{displayName:user.displayName,email:user.email,role:user.role,team:user.team,status:user.status}:blank);setModal(true)}
  async function save(event:FormEvent){event.preventDefault(); if(preview){if(editing)setUsers(list=>list.map(user=>user.id===editing?{...user,...form}:user));else setInvites(list=>[{id:Date.now(),...form,createdAt:new Date().toISOString()},...list]);setMessage(editing?"Kullanıcı güncellendi.":"Kullanıcı daveti oluşturuldu.");setModal(false);return} const response=await fetch("/api/admin/users",{method:editing?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,id:editing})});const data=await response.json();setMessage(response.ok?(editing?"Kullanıcı güncellendi.":"Kullanıcı daveti oluşturuldu."):data.error);if(response.ok){setModal(false);await load()}}
  async function inviteAction(id:number,action:"resend"|"cancel"){if(preview){if(action==="cancel")setInvites(list=>list.filter(invite=>invite.id!==id));setMessage(action==="resend"?"Davet yeniden oluşturuldu.":"Davet iptal edildi.");return}await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,action})});await load()}
  function exportCsv(){const rows=[["Ad Soyad","E-posta","Rol","Ekip","Durum"],...filtered.map(user=>[user.displayName,user.email,roles[user.role],user.team,user.status])];const blob=new Blob(["\uFEFF"+rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(";")).join("\r\n")],{type:"text/csv;charset=utf-8"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="op8-kullanicilar.csv";link.click();URL.revokeObjectURL(link.href);setMessage(`${filtered.length} kullanıcı dışa aktarıldı.`)}
  async function importCsv(file?:File){if(!file)return;const text=await file.text();const rows=text.replace(/^\uFEFF/,"").split(/\r?\n/).slice(1).filter(Boolean);let count=0;for(const row of rows){const [displayName,email,roleName,teamName]=row.split(";").map(value=>value.replace(/^"|"$/g,"").trim());if(!email)continue;const roleKey=Object.entries(roles).find(([,label])=>label===roleName)?.[0]||"member";if(preview){setInvites(list=>[{id:Date.now()+count,email,displayName:displayName||email.split("@")[0],role:roleKey,team:teamName||"Genel",createdAt:new Date().toISOString()},...list])}else await fetch("/api/admin/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,displayName,role:roleKey,team:teamName||"Genel"})});count++}setMessage(`${count} kullanıcı daveti içe aktarıldı.`);await load()}
  const stats=[{label:"Toplam Kullanıcı",value:users.length,tone:"blue",icon:"◎"},{label:"Aktif Kullanıcı",value:users.filter(u=>u.status==="active").length,tone:"green",icon:"✓"},{label:"Yöneticiler",value:users.filter(u=>["super_admin","admin"].includes(u.role)).length,tone:"orange",icon:"♙"},{label:"Editörler",value:users.filter(u=>u.role==="editor").length,tone:"purple",icon:"◇"},{label:"Üyeler",value:users.filter(u=>["author","member"].includes(u.role)).length,tone:"teal",icon:"◉"},{label:"Davetler",value:invites.length,tone:"pink",icon:"♧"}];
  return <section className="users-page">
    <header className="users-title"><div><h1>Kullanıcılar</h1><p>Sistem kullanıcılarını, rolleri, izinleri ve erişimi yönetin.</p></div><div className="users-actions"><input aria-label="Kullanıcı ara" placeholder="Ad veya e-posta ara..." value={query} onChange={e=>setQuery(e.target.value)}/><button className="primary" onClick={()=>openEditor()}>＋ Kullanıcı Ekle</button><button onClick={()=>importRef.current?.click()}>⇩ İçe Aktar</button><button onClick={exportCsv}>⇧ Dışa Aktar</button><input ref={importRef} hidden type="file" accept=".csv,text/csv" onChange={e=>void importCsv(e.target.files?.[0])}/></div></header>
    {message&&<button className="users-message" onClick={()=>setMessage("")}>{message} ×</button>}
    <div className="users-stats">{stats.map(stat=><article key={stat.label}><i className={stat.tone}>{stat.icon}</i><span><small>{stat.label}</small><strong>{stat.value}</strong><em>Güncel kullanıcı verisi</em></span></article>)}</div>
    <div className="users-layout"><main className="users-main"><nav className="users-tabs">{[["all","Tüm Kullanıcılar"],["admins","Yöneticiler"],["editors","Editörler"],["members","Üyeler"],["invited","Davetliler"],["disabled","Devre Dışı"]].map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}</button>)}</nav>
      <div className="users-filters"><input placeholder="Kullanıcı ara..." value={query} onChange={e=>setQuery(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value)}><option value="all">Tüm Roller</option>{Object.entries(roles).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tüm Durumlar</option><option value="active">Aktif</option><option value="disabled">Devre Dışı</option></select><select value={team} onChange={e=>setTeam(e.target.value)}><option value="all">Tüm Ekipler</option>{[...new Set(users.map(u=>u.team))].map(value=><option key={value}>{value}</option>)}</select><span/><button className={!grid?"active":""} onClick={()=>setGrid(false)}>☷</button><button className={grid?"active":""} onClick={()=>setGrid(true)}>▦</button></div>
      {tab==="invited"?<InviteList invites={invites} action={inviteAction}/>:grid?<div className="users-grid">{pageUsers.map(user=><UserCard key={user.id} user={user} edit={openEditor}/>)}</div>:<UserTable users={pageUsers} edit={openEditor}/>} 
      <footer className="users-pagination"><span>Toplam {filtered.length} kullanıcı</span><div><button disabled={page===1} onClick={()=>setPage(page-1)}>‹</button>{Array.from({length:totalPages},(_,index)=><button key={index} className={page===index+1?"active":""} onClick={()=>setPage(index+1)}>{index+1}</button>)}<button disabled={page===totalPages} onClick={()=>setPage(page+1)}>›</button></div><label>Sayfa başına <select value={size} onChange={e=>setSize(Number(e.target.value))}><option>5</option><option>10</option><option>20</option></select></label></footer>
    </main><aside className="users-aside"><Panel title="Rol Dağılımı"><div className="role-donut"><b>{users.length}<small>Toplam</small></b></div>{Object.entries(roles).map(([key,label])=><p className="metric" key={key}><span>{label}</span><b>{users.filter(user=>user.role===key).length}</b></p>)}</Panel><Panel title="Son Aktiviteler">{activities.length?activities.slice(0,5).map(item=><p className="activity" key={item.id}><b>{item.description}</b><small>{formatDate(item.createdAt)}</small></p>):<p className="activity"><b>Henüz aktivite yok</b><small>Yeni işlemler burada gösterilecek.</small></p>}</Panel><Panel title="Bekleyen Davetler"><InviteList invites={invites.slice(0,4)} action={inviteAction}/></Panel></aside></div>
    {modal&&<div className="users-modal"><form onSubmit={save}><header><h2>{editing?"Kullanıcıyı Düzenle":"Kullanıcı Davet Et"}</h2><button type="button" onClick={()=>setModal(false)}>×</button></header><label>Ad ve soyad<input required value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></label><label>E-posta<input required type="email" disabled={Boolean(editing)} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Rol<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{Object.entries(roles).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Ekip<input value={form.team} onChange={e=>setForm({...form,team:e.target.value})}/></label>{editing&&<label>Durum<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Aktif</option><option value="disabled">Devre Dışı</option></select></label>}<footer><button type="button" onClick={()=>setModal(false)}>Vazgeç</button><button className="primary">{editing?"Kaydet":"Davet Gönder"}</button></footer></form></div>}
  </section>
}

function UserTable({users,edit}:{users:User[];edit:(user:User)=>void}){return <div className="users-table"><table><thead><tr><th>Kullanıcı</th><th>Rol</th><th>Ekip</th><th>Durum</th><th>Son giriş</th><th>Katılım</th><th>İşlemler</th></tr></thead><tbody>{users.map(user=><tr key={user.id}><td><i>{initials(user.displayName)}</i><strong>{user.displayName}<small>{user.email}</small></strong></td><td><span className={`role ${user.role}`}>{roles[user.role]||user.role}</span></td><td>{user.team}</td><td><span className={`status ${user.status}`}>{user.status==="active"?"Aktif":"Devre Dışı"}</span></td><td>{formatDate(user.lastLoginAt)}</td><td>{formatDate(user.createdAt)}</td><td><button aria-label="Kullanıcıyı düzenle" onClick={()=>edit(user)}>✎</button><button aria-label="Yetkileri düzenle" onClick={()=>edit(user)}>⚿</button></td></tr>)}</tbody></table></div>}
function UserCard({user,edit}:{user:User;edit:(user:User)=>void}){return <article><i>{initials(user.displayName)}</i><h3>{user.displayName}</h3><p>{user.email}</p><b className={`role ${user.role}`}>{roles[user.role]}</b><span>{user.team}</span><button onClick={()=>edit(user)}>Düzenle</button></article>}
function InviteList({invites,action}:{invites:Invite[];action:(id:number,action:"resend"|"cancel")=>void}){return <div className="invite-list">{invites.length?invites.map(invite=><p key={invite.id}><b>{invite.email}<small>{roles[invite.role]} · {invite.team}</small></b><button onClick={()=>action(invite.id,"resend")}>Yenile</button><button onClick={()=>action(invite.id,"cancel")}>×</button></p>):<p>Davet bulunmuyor.</p>}</div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className="users-panel"><h2>{title}</h2>{children}</section>}
function initials(value:string){return value.split(/\s+/).slice(0,2).map(part=>part[0]).join("").toUpperCase()}
function formatDate(value:string|null){return value?new Date(value).toLocaleDateString("tr-TR"):"—"}
