"use client";
import { useEffect, useState } from "react";
type Opportunity = { id: number; title: string; description: string; engine: string; contentType: string; priority: string; focusKeyword: string; suggestedPublishAt: string | null };
const labels: Record<string, string> = { high: "Yüksek", medium: "Orta", low: "Düşük", article: "Makale", template: "Şablon" };
export default function ContentOpportunityPlanner() {
  const [items, setItems] = useState<Opportunity[]>([]), [busy, setBusy] = useState(true), [message, setMessage] = useState("");
  async function load() { setBusy(true); const response = await fetch("/api/admin/content-opportunities"), data = await response.json(); if (response.ok) setItems(data.items || []); else setMessage(data.error || "İçerik fırsatları yüklenemedi."); setBusy(false); }
  useEffect(() => { load(); }, []);
  async function act(id: number, action: "convert" | "dismiss") { const response = await fetch("/api/admin/content-opportunities", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, action }) }), data = await response.json(); if (!response.ok) { setMessage(data.error || "İşlem tamamlanamadı."); return; } setMessage(action === "convert" ? "Fırsat, Fikir aşamasında yeni içeriğe dönüştürüldü." : "Fırsat listeden kaldırıldı."); await load(); }
  return <section className="opportunity-planner"><header><div><h2>İçerik fırsatları ve planı</h2><p>Framework kapsamı, içerik yoğunluğu, kategori, etiket ve anahtar kelime eksiklerinden otomatik oluşturulur.</p></div><button onClick={load}>↻ Yeniden analiz et</button></header>{message && <p className="opportunity-message" role="status">{message}</p>}<div className="opportunity-grid">{busy ? <p>Analiz ediliyor…</p> : items.map((item) => <article key={item.id}><div><span className={`priority ${item.priority}`}>{labels[item.priority] || item.priority}</span><span>{item.engine}</span></div><h3>{item.title}</h3><p>{item.description}</p><dl><div><dt>İçerik tipi</dt><dd>{labels[item.contentType] || item.contentType}</dd></div><div><dt>Odak kelime</dt><dd>{item.focusKeyword}</dd></div><div><dt>Önerilen tarih</dt><dd>{item.suggestedPublishAt ? new Date(item.suggestedPublishAt).toLocaleDateString("tr-TR") : "—"}</dd></div></dl><footer><button onClick={() => act(item.id, "dismiss")}>Geç</button><button className="convert" onClick={() => act(item.id, "convert")}>Fikre dönüştür</button></footer></article>)}{!busy && !items.length && <p>Yeni içerik açığı bulunmadı.</p>}</div></section>;
}
