"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import RichTextEditor from "./RichTextEditor";
import TextStyleControls,{defaultExcerptStyle,defaultTitleStyle,TextStyle} from "./TextStyleControls";
type Category={id:number;name:string};
type Capabilities={publish:boolean;delete:boolean;ownOnly:boolean};
type Post={id:number;title:string;slug:string;excerpt:string;content:string;status:string;categoryId:number|null;categoryName?:string|null;coverUrl:string;coverAlt:string;seoTitle:string;seoDescription:string;publishedAt:string|null;updatedAt:string};
const empty={title:"",slug:"",excerpt:"",content:"",status:"draft",categoryId:"",coverUrl:"",coverAlt:"",seoTitle:"",seoDescription:"",publishedAt:""};
const styleMarker=(title:TextStyle,excerpt:TextStyle)=>`<!--op8-style:${JSON.stringify({title,excerpt})}-->`;
function readStyles(content:string){const match=content.match(/^<!--op8-style:(.*?)-->/);if(!match)return{title:defaultTitleStyle,excerpt:defaultExcerptStyle,content};try{const value=JSON.parse(match[1]);return{title:value.title||defaultTitleStyle,excerpt:value.excerpt||defaultExcerptStyle,content:content.slice(match[0].length)}}catch{return{title:defaultTitleStyle,excerpt:defaultExcerptStyle,content}}}
export default function PostManagerRich(){
 const[posts,setPosts]=useState<Post[]>([]),[categories,setCategories]=useState<Category[]>([]),[capabilities,setCapabilities]=useState<Capabilities>({publish:false,delete:false,ownOnly:false}),[form,setForm]=useState(empty),[titleStyle,setTitleStyle]=useState<TextStyle>(defaultTitleStyle),[excerptStyle,setExcerptStyle]=useState<TextStyle>(defaultExcerptStyle),[editing,setEditing]=useState<Post|null>(null),[query,setQuery]=useState(""),[filter,setFilter]=useState("all"),[open,setOpen]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(true),[saving,setSaving]=useState(false),[dirty,setDirty]=useState(false);
 async function load(){setBusy(true);try{const r=await fetch("/api/admin/posts"),d=await r.json();if(r.ok){setPosts(d.posts||[]);setCategories(d.categories||[]);setCapabilities(d.capabilities||capabilities)}else setMessage(d.error||"YazÄ±lar yÃ¼klenemedi.")}catch{setMessage("YazÄ±lar yÃ¼klenemedi.")}finally{setBusy(false)}}
 useEffect(()=>{load()},[]);useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
 const visible=useMemo(()=>posts.filter(p=>(filter==="all"||p.status===filter)&&p.title.toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR"))),[posts,query,filter]);const count=(s:string)=>s==="all"?posts.length:posts.filter(p=>p.status===s).length;
 function change(next:typeof empty){setForm(next);setDirty(true)}function close(){if(!dirty||confirm("KaydedilmemiÅŸ deÄŸiÅŸiklikler silinsin mi?")){setOpen(false);setDirty(false)}}
 function create(){setEditing(null);setForm(empty);setTitleStyle(defaultTitleStyle);setExcerptStyle(defaultExcerptStyle);setMessage("");setDirty(false);setOpen(true)}
 function edit(p:Post){const s=readStyles(p.content||"");setTitleStyle(s.title);setExcerptStyle(s.excerpt);setEditing(p);setForm({title:p.title,slug:p.slug,excerpt:p.excerpt||"",content:s.content,status:p.status,categoryId:p.categoryId?String(p.categoryId):"",coverUrl:p.coverUrl||"",coverAlt:p.coverAlt||"",seoTitle:p.seoTitle||"",seoDescription:p.seoDescription||"",publishedAt:p.publishedAt?p.publishedAt.slice(0,16):""});setDirty(false);setOpen(true)}
 async function save(e:FormEvent){e.preventDefault();setSaving(true);try{const r=await fetch("/api/admin/posts",{method:editing?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,content:styleMarker(titleStyle,excerptStyle)+form.content,id:editing?.id,categoryId:form.categoryId?Number(form.categoryId):null,publishedAt:form.publishedAt?new Date(form.publishedAt).toISOString():null})}),d=await r.json();if(!r.ok){setMessage(d.error||"YazÄ± kaydedilemedi.");return}setDirty(false);setOpen(false);setMessage(editing?"YazÄ± gÃ¼ncellendi.":"YazÄ± oluÅŸturuldu.");await load()}finally{setSaving(false)}}
 async function status(id:number,value:string){await fetch("/api/admin/posts",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status:value})});await load()}async function remove(p:Post){if(!confirm(`â€œ${p.title}â€ kalÄ±cÄ± olarak silinsin mi?`))return;await fetch("/api/admin/posts",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:p.id})});await load()}
 return <div className="post-admin"><div className="admin-title"><div><p className="eyebrow">Ä°Ã‡ERÄ°K YÃ–NETÄ°MÄ°</p><h1>YazÄ±lar</h1><p>Word benzeri editÃ¶rle zengin iÃ§erikler oluÅŸturun.</p></div><button className="admin-primary top" onClick={create}>+ Yeni yazÄ±</button></div>{message&&<p className="admin-message">{message}</p>}<div className="post-toolbar"><input className="post-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="YazÄ±larda araâ€¦"/><div className="status-tabs">{[["all","TÃ¼mÃ¼"],["draft","Taslak"],["published","YayÄ±nda"],["scheduled","ZamanlandÄ±"]].map(([s,l])=><button className={filter===s?"active":""} onClick={()=>setFilter(s)} key={s}>{l} <span>{count(s)}</span></button>)}</div></div><section className="post-table"><div className="post-table-head"><span>YazÄ±</span><span>Kategori</span><span>Durum</span><span>Ä°ÅŸlemler</span></div>{busy?<p className="loading-row">YÃ¼kleniyorâ€¦</p>:visible.map(p=><article className="post-admin-row" key={p.id}><div><h3>{p.title}</h3><p>/{p.slug}</p><small>{p.excerpt||"Ã–zet eklenmemiÅŸ"}</small></div><span>{p.categoryName||"Kategorisiz"}</span><span className={`status-badge ${p.status}`}>{p.status==="published"?"YayÄ±nda":p.status==="scheduled"?"ZamanlandÄ±":"Taslak"}</span><div className="post-row-actions"><button onClick={()=>edit(p)}>DÃ¼zenle</button>{capabilities.publish&&<button onClick={()=>status(p.id,p.status==="published"?"draft":"published")}>{p.status==="published"?"TaslaÄŸa al":"YayÄ±nla"}</button>}{capabilities.delete&&<button className="danger" onClick={()=>remove(p)}>Sil</button>}</div></article>)}</section>
 {open&&<div className="editor-overlay" role="dialog" aria-modal="true"><form className="post-editor rich-post-editor" onSubmit={save}><header><div><p className="eyebrow">{editing?"YAZIYI DÃœZENLE":"YENÄ° YAZI"}</p><h2>{form.title||"BaÅŸlÄ±ksÄ±z yazÄ±"}</h2></div><button type="button" aria-label="EditÃ¶rÃ¼ kapat" onClick={close}>Ã—</button></header><div className="editor-grid"><div className="editor-main"><label>BaÅŸlÄ±k<input required value={form.title} onChange={e=>change({...form,title:e.target.value})}/></label><h3 className="style-section-title">BaÅŸlÄ±k gÃ¶rÃ¼nÃ¼mÃ¼</h3><TextStyleControls value={titleStyle} onChange={v=>{setTitleStyle(v);setDirty(true)}}/><label>Slug<input value={form.slug} onChange={e=>change({...form,slug:e.target.value})}/></label><label>KÄ±sa Ã¶zet<textarea rows={3} maxLength={240} value={form.excerpt} onChange={e=>change({...form,excerpt:e.target.value})}/><small>{form.excerpt.length}/240</small></label><h3 className="style-section-title">KÄ±sa Ã¶zet gÃ¶rÃ¼nÃ¼mÃ¼</h3><TextStyleControls value={excerptStyle} onChange={v=>{setExcerptStyle(v);setDirty(true)}}/><label>Ä°Ã§erik<RichTextEditor value={form.content} onChange={content=>{setForm(current=>({...current,content}));setDirty(true)}}/></label><fieldset><legend>SEO alanlarÄ±</legend><label>SEO baÅŸlÄ±ÄŸÄ±<input maxLength={60} value={form.seoTitle} onChange={e=>change({...form,seoTitle:e.target.value})}/></label><label>Meta aÃ§Ä±klama<textarea rows={3} maxLength={160} value={form.seoDescription} onChange={e=>change({...form,seoDescription:e.target.value})}/></label></fieldset></div><aside className="editor-side"><label>Durum<select value={form.status} disabled={!capabilities.publish} onChange={e=>change({...form,status:e.target.value})}><option value="draft">Taslak</option><option value="published">YayÄ±nda</option><option value="scheduled">ZamanlandÄ±</option></select></label><label>Kategori<select value={form.categoryId} onChange={e=>change({...form,categoryId:e.target.value})}><option value="">Kategorisiz</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Kapak gÃ¶rseli URL<input value={form.coverUrl} placeholder="/api/media/... veya https://..." onChange={e=>change({...form,coverUrl:e.target.value})}/></label><label>GÃ¶rsel alt metni<input value={form.coverAlt} onChange={e=>change({...form,coverAlt:e.target.value})}/></label><div className="editor-actions"><button type="button" onClick={close}>VazgeÃ§</button><button className="admin-primary" disabled={saving} type="submit">{saving?"Kaydediliyorâ€¦":"Kaydet"}</button></div></aside></div></form></div>}</div>}
