"use client";
import {useEffect,useRef,useState} from "react";
type MediaItem={id:number;name:string;url:string;alt:string;mimeType:string};
const fonts=["Arial","Georgia","Verdana","Tahoma","Trebuchet MS","Times New Roman"];
const sizes=[{label:"10",value:"1"},{label:"12",value:"2"},{label:"14",value:"3"},{label:"18",value:"4"},{label:"24",value:"5"},{label:"32",value:"6"},{label:"48",value:"7"}];
const htmlValue=(value:string)=>/<[a-z][\s\S]*>/i.test(value)?value:value.split(/\n{2,}/).filter(Boolean).map(p=>`<p>${p.replace(/\n/g,"<br>")}</p>`).join("");
export default function RichTextEditor({value,onChange}:{value:string;onChange:(value:string)=>void}){
 const editor=useRef<HTMLDivElement>(null),[media,setMedia]=useState<MediaItem[]>([]),[showMedia,setShowMedia]=useState(false);
 useEffect(()=>{if(editor.current&&editor.current.innerHTML!==htmlValue(value))editor.current.innerHTML=htmlValue(value)},[value]);
 useEffect(()=>{fetch("/api/admin/modules?module=media").then(r=>r.ok?r.json():{items:[]}).then(d=>setMedia((d.items||[]).filter((x:MediaItem)=>x.mimeType?.startsWith("image/")))).catch(()=>{})},[]);
 const sync=()=>onChange(editor.current?.innerHTML||"");
 const command=(name:string,arg?:string)=>{editor.current?.focus();document.execCommand(name,false,arg);sync()};
 const insertImage=(url:string,alt="")=>{editor.current?.focus();document.execCommand("insertHTML",false,`<figure><img src="${url.replaceAll('"','&quot;')}" alt="${alt.replaceAll('"','&quot;')}"><figcaption>Görsel açıklaması</figcaption></figure><p><br></p>`);sync();setShowMedia(false)};
 const addLink=()=>{const url=prompt("Bağlantı adresi (https://…)");if(url)command("createLink",url)};
 const addImageUrl=()=>{const url=prompt("Görsel adresi (https://…)");if(url)insertImage(url)};
 return <div className="rich-editor-wrap"><div className="rich-toolbar" role="toolbar" aria-label="İçerik biçimlendirme araçları"><select aria-label="Paragraf biçimi" defaultValue="p" onChange={e=>command("formatBlock",e.target.value)}><option value="p">Paragraf</option><option value="h2">Başlık 2</option><option value="h3">Başlık 3</option><option value="blockquote">Alıntı</option></select><select aria-label="Yazı tipi" defaultValue="Arial" onChange={e=>command("fontName",e.target.value)}>{fonts.map(font=><option key={font}>{font}</option>)}</select><select aria-label="Yazı boyutu" defaultValue="3" onChange={e=>command("fontSize",e.target.value)}>{sizes.map(size=><option value={size.value} key={size.value}>{size.label} px</option>)}</select><label className="toolbar-color" title="Yazı rengi"><span>A</span><input type="color" defaultValue="#18352e" onChange={e=>command("foreColor",e.target.value)}/></label><button type="button" onClick={()=>command("bold")} title="Kalın"><b>K</b></button><button type="button" onClick={()=>command("italic")} title="İtalik"><i>İ</i></button><button type="button" onClick={()=>command("underline")} title="Altı çizili"><u>A</u></button><button type="button" onClick={()=>command("justifyLeft")} title="Sola hizala">☰</button><button type="button" onClick={()=>command("justifyCenter")} title="Ortala">≡</button><button type="button" onClick={()=>command("justifyRight")} title="Sağa hizala">☷</button><button type="button" onClick={()=>command("insertUnorderedList")}>• Liste</button><button type="button" onClick={()=>command("insertOrderedList")}>1. Liste</button><button type="button" onClick={addLink}>🔗</button><button type="button" onClick={()=>setShowMedia(!showMedia)}>Görsel</button><button type="button" onClick={addImageUrl}>URL görsel</button><button type="button" onClick={()=>command("removeFormat")}>Temizle</button><button type="button" onClick={()=>command("undo")}>↶</button><button type="button" onClick={()=>command("redo")}>↷</button></div>{showMedia&&<div className="inline-media-picker">{media.length?media.map(item=><button type="button" onClick={()=>insertImage(item.url,item.alt||item.name)} key={item.id}><img src={item.url} alt={item.alt||item.name}/><span>{item.name}</span></button>):<p>Medya kütüphanesinde kullanılabilir görsel yok. “URL görsel” seçeneğini kullanabilirsiniz.</p>}</div>}<div ref={editor} className="rich-editor" contentEditable suppressContentEditableWarning onInput={sync} onBlur={sync} data-placeholder="Yazınızı buraya yazın…"/></div>
}
