export type MenuItem={id:string;label:string;href:string;visible:boolean};
export type HomeSection={id:string;type:"featured"|"latest"|"topics"|"content"|"newsletter";title:string;eyebrow:string;body:string;visible:boolean;postIds:number[];imageUrl:string;imageAlt:string;buttonLabel:string;buttonHref:string};
export type ThemeConfig={ink:string;paper:string;cream:string;accent:string;line:string;muted:string;headingFont:string;bodyFont:string};
export type HeroTextStyle={fontFamily:string;fontSize:number;color:string};export type HeroBox={x:number;y:number;width:number;height:number};export type HeroLayout={eyebrow:HeroBox;title:HeroBox;accent:HeroBox;description:HeroBox;button:HeroBox};
export type HomeConfig={theme:ThemeConfig;brand:{siteName:string;logoUrl:string;logoAlt:string;logoWidth:number};headerMenu:MenuItem[];hero:{eyebrow:string;title:string;accent:string;description:string;buttonLabel:string;buttonHref:string;imageUrl:string;imageAlt:string;eyebrowStyle:HeroTextStyle;titleStyle:HeroTextStyle;accentStyle:HeroTextStyle;descriptionStyle:HeroTextStyle;layout:HeroLayout};sections:HomeSection[]};
const section=(id:string,type:HomeSection["type"],title:string,eyebrow:string,postIds:number[]=[]):HomeSection=>({id,type,title,eyebrow,body:"",visible:true,postIds,imageUrl:"",imageAlt:"",buttonLabel:"",buttonHref:""});
export const defaultTheme:ThemeConfig={ink:"#18352e",paper:"#f5f1e8",cream:"#ebe4d6",accent:"#ee7551",line:"#c9c1b2",muted:"#6f766f",headingFont:"Georgia, 'Times New Roman', serif",bodyFont:"Arial, Helvetica, sans-serif"};
export const defaultHeroLayout:HeroLayout={eyebrow:{x:5,y:10,width:60,height:8},title:{x:5,y:27,width:88,height:16},accent:{x:5,y:49,width:78,height:12},description:{x:5,y:65,width:78,height:18},button:{x:5,y:87,width:24,height:8}};
export const defaultHomeConfig:HomeConfig={theme:defaultTheme,brand:{siteName:"OP8 Operating Partner Value Creation Framework",logoUrl:"",logoAlt:"OP8 logosu",logoWidth:132},headerMenu:[{id:"posts",label:"Yazılar",href:"#yazilar",visible:true},{id:"topics",label:"Konular",href:"#konular",visible:true},{id:"about",label:"Hakkında",href:"#hakkinda",visible:true}],hero:{eyebrow:"OP8 OPERATING PARTNER VALUE CREATION FRAMEWORK",title:"Şirket Performansını Sistematik Bir Değer Yaratma Modeline Dönüştürün.",accent:"8 Value Engine. Tek Entegre Framework.",description:"OP8; bağlantılı değer motorlarını tek bir yönetim sistemi altında birleştirir.",buttonLabel:"Son yazıları keşfet",buttonHref:"#yazilar",imageUrl:"",imageAlt:"",eyebrowStyle:{fontFamily:"Arial, Helvetica, sans-serif",fontSize:14,color:"#f5f1e8"},titleStyle:{fontFamily:"Georgia, 'Times New Roman', serif",fontSize:48,color:"#f5f1e8"},accentStyle:{fontFamily:"Georgia, 'Times New Roman', serif",fontSize:28,color:"#ee7551"},descriptionStyle:{fontFamily:"Georgia, 'Times New Roman', serif",fontSize:20,color:"#f5f1e8"},layout:defaultHeroLayout},sections:[section("featured","featured","Öne çıkan yazı","EDİTÖRÜN SEÇİMİ",[1]),section("latest","latest","Son yazılar","ARŞİVDEN YENİLER",[2,3,4]),section("topics","topics","Merak ettiğin yerden başla.","KONU BAŞLIKLARI")]};
export function normalizeHomeConfig(value:Partial<HomeConfig>):HomeConfig{const hero={...defaultHomeConfig.hero,...value.hero};const layout=value.hero?.layout;return{...defaultHomeConfig,...value,theme:{...defaultTheme,...value.theme},brand:{...defaultHomeConfig.brand,...value.brand},headerMenu:value.headerMenu??defaultHomeConfig.headerMenu,hero:{...hero,eyebrowStyle:{...defaultHomeConfig.hero.eyebrowStyle,...value.hero?.eyebrowStyle},titleStyle:{...defaultHomeConfig.hero.titleStyle,...value.hero?.titleStyle},accentStyle:{...defaultHomeConfig.hero.accentStyle,...value.hero?.accentStyle},descriptionStyle:{...defaultHomeConfig.hero.descriptionStyle,...value.hero?.descriptionStyle},layout:{eyebrow:{...defaultHeroLayout.eyebrow,...layout?.eyebrow},title:{...defaultHeroLayout.title,...layout?.title},accent:{...defaultHeroLayout.accent,...layout?.accent},description:{...defaultHeroLayout.description,...layout?.description},button:{...defaultHeroLayout.button,...layout?.button}}},sections:(value.sections??defaultHomeConfig.sections).map(s=>({...section(s.id,s.type,s.title,s.eyebrow,s.postIds),...s}))}}
