Exit code: 0
Wall time: 2.6 seconds
Output:
export type MenuItem={id:string;label:string;href:string;visible:boolean};
export type HomeSection={id:string;type:"featured"|"latest"|"topics"|"content"|"newsletter";title:string;eyebrow:string;body:string;visible:boolean;postIds:number[];imageUrl:string;imageAlt:string;buttonLabel:string;buttonHref:string};
export type ThemeConfig={ink:string;paper:string;cream:string;accent:string;line:string;muted:string;headingFont:string;bodyFont:string};
export type HeroTextStyle={fontFamily:string;fontSize:number;color:string};
export type HomeConfig={theme:ThemeConfig;brand:{siteName:string;logoUrl:string;logoAlt:string;logoWidth:number};headerMenu:MenuItem[];hero:{eyebrow:string;title:string;accent:string;description:string;buttonLabel:string;buttonHref:string;imageUrl:string;imageAlt:string;eyebrowStyle:HeroTextStyle;titleStyle:HeroTextStyle;accentStyle:HeroTextStyle;descriptionStyle:HeroTextStyle};sections:HomeSection[]};
const section=(id:string,type:HomeSection["type"],title:string,eyebrow:string,postIds:number[]=[]):HomeSection=>({id,type,title,eyebrow,body:"",visible:true,postIds,imageUrl:"",imageAlt:"",buttonLabel:"",buttonHref:""});
export const defaultTheme:ThemeConfig={ink:"#18352e",paper:"#f5f1e8",cream:"#ebe4d6",accent:"#ee7551",line:"#c9c1b2",muted:"#6f766f",headingFont:"Georgia, 'Times New Roman', serif",bodyFont:"Arial, Helvetica, sans-serif"};
export const defaultHomeConfig:HomeConfig={theme:defaultTheme,brand:{siteName:"OP8 Operating Partner Value Creation Framework",logoUrl:"",logoAlt:"OP8 Operating Partner Value Creation Framework logosu",logoWidth:132},headerMenu:[{id:"posts",label:"Yazılar",href:"#yazilar",visible:true},{id:"topics",label:"Konular",href:"#konular",visible:true},{id:"about",label:"Hakkında",href:"#hakkinda",visible:true}],hero:{eyebrow:"DÜŞÜNCE • TEKNOLOJİ • GÜNLÜK HAYAT",title:"Daha iyi düşünmek için",accent:"biraz yavaşla.",description:"İş, teknoloji ve gündelik hayatın kesişiminden berrak fikirler. Gürültü değil, üzerinde durmaya değer yazılar.",buttonLabel:"Son yazıları keşfet",buttonHref:"#yazilar",imageUrl:"",imageAlt:"",eyebrowStyle:{fontFamily:"Arial, Helvetica, sans-serif",fontSize:11,color:"#f5f1e8"},titleStyle:{fontFamily:"Georgia, 'Times New Roman', serif",fontSize:78,color:"#f5f1e8"},accentStyle:{fontFamily:"Georgia, 'Times New Roman', serif",fontSize:78,color:"#ee7551"},descriptionStyle:{fontFamily:"Georgia, 'Times New Roman', serif",fontSize:20,color:"#f5f1e8"}},sections:[section("featured","featured","Öne çıkan yazı","EDİTÖRÜN SEÇİMİ",[1]),section("latest","latest","Son yazılar","ARŞİVDEN YENİLER",[2,3,4]),section("topics","topics","Merak ettiğin yerden başla.","KONU BAŞLIKLARI")]};
export function normalizeHomeConfig(value:Partial<HomeConfig>):HomeConfig{const hero={...defaultHomeConfig.hero,...value.hero};return{...defaultHomeConfig,...value,theme:{...defaultTheme,...value.theme},brand:{...defaultHomeConfig.brand,...value.brand},headerMenu:value.headerMenu??defaultHomeConfig.headerMenu,hero:{...hero,eyebrowStyle:{...defaultHomeConfig.hero.eyebrowStyle,...value.hero?.eyebrowStyle},titleStyle:{...defaultHomeConfig.hero.titleStyle,...value.hero?.titleStyle},accentStyle:{...defaultHomeConfig.hero.accentStyle,...value.hero?.accentStyle},descriptionStyle:{...defaultHomeConfig.hero.descriptionStyle,...value.hero?.descriptionStyle}},sections:(value.sections??defaultHomeConfig.sections).map(s=>({...section(s.id,s.type,s.title,s.eyebrow,s.postIds),...s}))}}

