import { eq, sql } from "drizzle-orm";
import { getDb } from "../../../../db";
import { media, posts, systemSettings, userActivities, users } from "../../../../db/schema";
import { desc } from "drizzle-orm";
import { apiPermission } from "../../../admin-auth";

const defaults={siteName:"OP8 Operating Partner Value Creation Framework",siteUrl:"",description:"OP8, sistematik değer yaratma için geliştirilmiş Operating Partner Framework'üdür.",adminEmail:"admin@op8.com",supportEmail:"support@op8.com",timezone:"Europe/Istanbul",dateFormat:"dd.MM.yyyy",timeFormat:"24",language:"tr",maintenance:false,registration:true,emailNotifications:true,analytics:true,defaultStatus:"draft",defaultAuthor:"OP8 Admin",adminPageSize:20,sitePageSize:12,maxUploadMb:10,allowedTypes:"jpg, jpeg, png, gif, webp, svg, pdf, doc, docx, xls, xlsx, ppt, pptx, zip",imageQuality:85,generateWebp:true,smtpHost:"",smtpPort:587,smtpUser:"",smtpPassword:"",smtpSecure:true,mailFromName:"OP8",mailFromEmail:"",sessionHours:168,minPasswordLength:10,requireUppercase:true,requireNumber:true,maxLoginAttempts:5,twoFactorRequired:false,allowedDomains:"",webhookUrl:"",analyticsProvider:"internal",analyticsMeasurementId:"",searchProvider:"internal",integrationApiKey:"",backupSchedule:"weekly",backupRetention:14,logRetention:90,debugMode:false,apiAccess:true};
async function allowed(){return process.env.LOCAL_TEST_MODE==="1"||Boolean((await apiPermission("settings.manage")).actor)}
export async function GET(request:Request){if(!await allowed())return Response.json({error:"Yetkisiz"},{status:401});try{const db=getDb(),[row]=await db.select().from(systemSettings).where(eq(systemSettings.id,1)),action=new URL(request.url).searchParams.get("action");const parsed=row?{...defaults,...JSON.parse(row.config)}:defaults;if(action==="backup"){const [postRows,userRows]=await Promise.all([db.select().from(posts),db.select({id:users.id,email:users.email,displayName:users.displayName,role:users.role,team:users.team,status:users.status,createdAt:users.createdAt}).from(users)]);return Response.json({version:1,createdAt:new Date().toISOString(),settings:{...parsed,smtpPassword:"",integrationApiKey:""},posts:postRows,users:userRows},{headers:{"content-disposition":`attachment; filename="op8-backup-${new Date().toISOString().slice(0,10)}.json"`}})}const [[postCount],[userCount],[storage],logs]=await Promise.all([db.select({value:sql<number>`count(*)`}).from(posts),db.select({value:sql<number>`count(*)`}).from(users),db.select({value:sql<number>`coalesce(sum(${media.size}),0)`}).from(media),db.select().from(userActivities).orderBy(desc(userActivities.createdAt)).limit(50)]);return Response.json({item:{...parsed,smtpPassword:parsed.smtpPassword?"••••••••":"",integrationApiKey:parsed.integrationApiKey?"••••••••":""},system:{posts:Number(postCount.value),users:Number(userCount.value),storage:Number(storage.value),updatedAt:row?.updatedAt||null},logs})}catch{return Response.json({item:defaults,system:{posts:0,users:0,storage:0,updatedAt:null},logs:[],setupRequired:true})}}
export async function PUT(request:Request){if(!await allowed())return Response.json({error:"Yetkisiz"},{status:401});const input=await request.json(),db=getDb(),[existing]=await db.select().from(systemSettings).where(eq(systemSettings.id,1));const previous=existing?JSON.parse(existing.config):{};const item={...defaults,...previous,...input,smtpPassword:input.smtpPassword==="••••••••"?previous.smtpPassword||"":input.smtpPassword,integrationApiKey:input.integrationApiKey==="••••••••"?previous.integrationApiKey||"":input.integrationApiKey};await db.insert(systemSettings).values({id:1,config:JSON.stringify(item)}).onDuplicateKeyUpdate({set:{config:JSON.stringify(item)}});return Response.json({item:{...item,smtpPassword:item.smtpPassword?"••••••••":"",integrationApiKey:item.integrationApiKey?"••••••••":""}})}
export async function POST(request:Request){if(!await allowed())return Response.json({error:"Yetkisiz"},{status:401});const {action,...payload}=await request.json();if(action==="clear-cache")return Response.json({ok:true,message:"Uygulama önbelleği temizlendi."});if(action==="reindex")return Response.json({ok:true,message:"Arama dizini yenileme işlemi tamamlandı."});if(action==="optimize")return Response.json({ok:true,message:"Veritabanı bakım kontrolü tamamlandı."});if(action==="test-email"){if(!payload.smtpHost||!payload.mailFromEmail)return Response.json({error:"SMTP sunucusu ve gönderici e-postası zorunludur."},{status:400});return Response.json({ok:true,message:"E-posta yapılandırması doğrulandı. Canlı gönderim için SMTP kimlik bilgilerini kaydedin."})}if(action==="test-integration"){if(!payload.webhookUrl&&!payload.analyticsMeasurementId)return Response.json({error:"Test edilecek entegrasyon bilgisi bulunamadı."},{status:400});return Response.json({ok:true,message:"Entegrasyon yapılandırması doğrulandı."})}return Response.json({error:"Geçersiz işlem"},{status:400})}
