"use client";
import{FormEvent,useEffect,useMemo,useState}from"react";
type Tag={id:number;name:string;slug:string;usageCount:number};
const colors=["blue","green","orange","purple","cyan","red","slate"];
const engine=(name:string)=>{const n=name.toLowerCase();return n.includes("growth")?"Growth":n.includes("ebitda")?"Profitability":n.includes("portfolio")?"Portfolio":n.includes("customer")?"Customer Success":n.includes("digital")?"Operations":"Value Creation"};
const category=(name:string)=>{const e=engine(name);return e==="Value Creation"?"Methodology":e};
export default function TagManager(){
 const[tags,setTags]=useState<Tag[]>([]),[busy,setBusy]=useState(true),[message,setMessage]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[engineFilter,setEngineFilter]=useState("all"),[page,setPage]=useState(1),[size,setSize]=useState(10),[selected,setSelected]=useState<number[]>([]),[modal,setModal]=useState(false),[settings,setSettings]=useState(false),[editing,setEditing]=useState<Tag|null>(null),[form,setForm]=useState({name:"",slug:""});
 async function load(){setBusy(true);const r=await fetch("/api/admin/modules?module=tags"),d=await r.json();if(r.ok)setTags(d.items);else setMessage(d.error);setBusy(false)}
 useEffect(()=>{load()},[]);
 const visible=useMemo(()=>tags.filter(t=>(status==="all"||(status==="active"?t.usageCount>0:t.usageCount===0))&&(engineFilter==="all"||engine(t.name)===engineFilter)&&`${t.name} ${t.slug}`.toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR"))),[tags,query,status,engineFilter]);
 const pages=Math.max(1,Math.ceil(visible.length/size)),current=Math.min(page,pages),items=visible.slice((current-1)*size,current*size);useEffect(()=>setPage(1),[query,status,engineFilter,size]);
 function create(){setEditing(null);setForm({name:"",slug:""});setModal(true)}function edit(t:Tag){setEditing(t);setForm({name:t.name,slug:t.slug});setModal(true)}
 async function save(e:FormEvent){e.preventDefault();const r=await fetch("/api/admin/modules?module=tags",{method:editing?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...form,id:editing?.id})}),d=await r.json();if(!r.ok)return setMessage(d.error);setModal(false);setMessage(editing?"Etiket güncellendi.":"Etiket oluşturuldu.");await load()}
 async function remove(t:Tag){if(!confirm(`“${t.name}” silinsin mi?`))return;await fetch("/api/admin/modules?module=tags",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id:t.id})});setMessage("Etiket silindi.");await load()}
 function exportCsv(){const csv="\uFEFFAd;Alias;Kullanım\r\n"+visible.map(t=>`"${t.name.replaceAll('"','""')}";${t.slug};${t.usageCount}`).join("\r\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="op8-etiketler.csv";a.click();URL.revokeObjectURL(a.href);setMessage(`${visible.length} etiket dışa aktarıldı.`)}
 const active=tags.filter(t=>t.usageCount>0).length,totalUsage=tags.reduce((n,t)=>n+t.usageCount,0),popular=[...tags].sort((a,b)=>b.usageCount-a.usageCount).slice(0,8),orphans=tags.filter(t=>!t.usageCount);
 return <div className="tags-admin"><header className="tags-head"><div><h1>Etiketler</h1><p>İçeriklerinizi daha iyi düzenlemek ve bağlamak için etiketleri yönetin.</p></div><div><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Etiket ara..."/></label><button className="tag-primary" onClick={create}>＋ Etiket Oluştur　⌄</button><button onClick={exportCsv}>⇩ Etiketleri Dışa Aktar</button><button onClick={()=>setSettings(true)}>⚙ Etiket Ayarları</button></div></header>{message&&<p className="admin-message" role="status">{message}</p>}
 <section className="tag-stats">{[["Toplam Etiket",tags.length,"#0872ed"],["Aktif Etiket",active,"#2da95c"],["Kullanılan Etiket",active,"#ffad00"],["Yetim Etiket",orphans.length,"#7844dd"],["İçerik Başına Ort.",tags.length?(totalUsage/tags.length).toFixed(1):"0","#12a6ae"]].map(([l,v,c])=><article style={{"--c":c}as React.CSSProperties} key={l}><i>◇</i><span><small>{l}</small><b>{v}</b><em>Genel durum</em></span></article>)}</section>
 <div className="tags-layout"><section className="tags-panel"><div className="tags-toolbar"><label>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ada göre etiket ara..."/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Tüm Durumlar</option><option value="active">Aktif</option><option value="orphan">Kullanılmıyor</option></select><select><option>Tüm Kategoriler</option></select><select value={engineFilter} onChange={e=>setEngineFilter(e.target.value)}><option value="all">Tüm Motorlar</option>{["Value Creation","Growth","Profitability","Portfolio","Customer Success","Operations"].map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>{setQuery("");setStatus("all");setEngineFilter("all")}}>Filtreleri Temizle</button></div><div className="tags-table-wrap"><table className="tags-table"><thead><tr><th><input type="checkbox" checked={selected.length===items.length&&items.length>0} onChange={e=>setSelected(e.target.checked?items.map(t=>t.id):[])}/></th><th></th><th>Etiket Adı</th><th>Alias</th><th>Kategori</th><th>Motor</th><th>Kullanım ↓</th><th>Durum</th><th>Güncellendi</th><th>İşlemler</th></tr></thead><tbody>{busy?<tr><td colSpan={10}>Yükleniyor…</td></tr>:items.map((t,i)=><tr key={t.id}><td><input type="checkbox" checked={selected.includes(t.id)} onChange={e=>setSelected(e.target.checked?[...selected,t.id]:selected.filter(id=>id!==t.id))}/></td><td>⠿</td><td><span className={`tag-chip ${colors[i%colors.length]}`}>{t.name}</span></td><td>{t.slug}</td><td>{category(t.name)}</td><td><span className="tag-engine"><i/> {engine(t.name)}</span></td><td><b>{t.usageCount}</b></td><td><span className={`tag-status ${t.usageCount?"active":"orphan"}`}>{t.usageCount?"Aktif":"Kullanılmıyor"}</span></td><td>Bugün</td><td><div className="tag-actions"><button onClick={()=>edit(t)} aria-label={`${t.name} düzenle`}>✎</button><button aria-label={`${t.name} analizi`}>▥</button><button onClick={()=>remove(t)} aria-label={`${t.name} sil`}>⋮</button></div></td></tr>)}</tbody></table></div><footer className="tag-pages"><span>{visible.length?`${(current-1)*size+1}–${Math.min(current*size,visible.length)} arası`:"0 sonuç"} · Toplam {visible.length}</span><div><button disabled={current===1} onClick={()=>setPage(current-1)}>‹</button>{Array.from({length:pages},(_,i)=>i+1).map(n=><button className={n===current?"active":""} onClick={()=>setPage(n)} key={n}>{n}</button>)}<button disabled={current===pages} onClick={()=>setPage(current+1)}>›</button></div><label>Sayfa başına<select value={size} onChange={e=>setSize(Number(e.target.value))}><option>5</option><option>10</option><option>20</option><option>50</option></select></label></footer></section>
 <aside className="tags-insights"><section><header><h2>Popüler Etiketler</h2><button>Tümünü gör</button></header><div className="tag-cloud">{popular.map((t,i)=><span className={`tag-chip ${colors[i%colors.length]}`} key={t.id}>{t.name} <b>{t.usageCount}</b></span>)}</div></section><section><h2>Etiket Kullanım Dağılımı</h2><div className="tag-donut"><i/><div><p><b>Yüksek (20+)</b> {tags.filter(t=>t.usageCount>=20).length}</p><p><b>Orta (5–19)</b> {tags.filter(t=>t.usageCount>=5&&t.usageCount<20).length}</p><p><b>Düşük (1–4)</b> {tags.filter(t=>t.usageCount>0&&t.usageCount<5).length}</p><p><b>Kullanılmıyor</b> {orphans.length}</p></div></div></section><section><h2>Son Aktiviteler</h2><p>Etiket sözlüğü yüklendi</p><p>{active} aktif etiket içeriklerde kullanılıyor</p></section><section><header><h2>Yetim Etiketler</h2></header><div className="tag-cloud">{orphans.slice(0,6).map(t=><span className="tag-chip slate" key={t.id}>{t.name}</span>)}{!orphans.length&&<p>Kullanılmayan etiket yok.</p>}</div></section></aside></div>
 {modal&&<div className="editor-overlay" role="dialog"><form className="tag-modal" onSubmit={save}><header><h2>{editing?"Etiketi düzenle":"Yeni etiket"}</h2><button type="button" onClick={()=>setModal(false)}>×</button></header><label>Etiket adı<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Alias / slug<input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} placeholder="Boşsa otomatik oluşturulur"/></label><div><button type="button" onClick={()=>setModal(false)}>Vazgeç</button><button className="tag-primary">Kaydet</button></div></form></div>}{settings&&<div className="editor-overlay" role="dialog"><section className="tag-modal"><header><h2>Etiket ayarları</h2><button onClick={()=>setSettings(false)}>×</button></header><label>Sayfa başına<select value={size} onChange={e=>setSize(Number(e.target.value))}><option>5</option><option>10</option><option>20</option></select></label><label><input type="checkbox" defaultChecked/> Kullanılmayan etiketleri uyar</label><button className="tag-primary" onClick={()=>{setSettings(false);setMessage("Etiket ayarları kaydedildi.")}}>Ayarları kaydet</button></section></div>}</div>
}
