import mysql from "mysql2/promise";

const pool=mysql.createPool({uri:process.env.DATABASE_URL,host:process.env.DB_HOST,port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:process.env.DB_NAME,multipleStatements:true});
const sql=`
CREATE TABLE IF NOT EXISTS categories (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(160) NOT NULL,slug VARCHAR(160) NOT NULL UNIQUE,description TEXT NOT NULL,color VARCHAR(20) NOT NULL DEFAULT '#ee7551',sort_order INT NOT NULL DEFAULT 0,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_categories_sort_order(sort_order));
CREATE TABLE IF NOT EXISTS posts (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL,slug VARCHAR(190) NOT NULL UNIQUE,excerpt TEXT NOT NULL,content LONGTEXT NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'draft',category_id INT NULL,cover_url TEXT NOT NULL,cover_alt VARCHAR(255) NOT NULL,seo_title VARCHAR(255) NOT NULL,seo_description TEXT NOT NULL,published_at TIMESTAMP NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_posts_category_id(category_id),INDEX idx_posts_status_published_at(status,published_at),CONSTRAINT fk_posts_category FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS tags (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(160) NOT NULL,slug VARCHAR(160) NOT NULL UNIQUE,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS post_tags (post_id INT NOT NULL,tag_id INT NOT NULL,PRIMARY KEY(post_id,tag_id),INDEX idx_post_tags_tag_id(tag_id),FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE,FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS media (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255) NOT NULL,\`key\` VARCHAR(255) NOT NULL UNIQUE,url TEXT NOT NULL,alt VARCHAR(255) NOT NULL,mime_type VARCHAR(120) NOT NULL,size BIGINT NOT NULL DEFAULT 0,content LONGBLOB NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS admin_users (id INT AUTO_INCREMENT PRIMARY KEY,user_id VARCHAR(190) NOT NULL UNIQUE,email VARCHAR(190) NOT NULL UNIQUE,display_name VARCHAR(190) NOT NULL,role VARCHAR(32) NOT NULL DEFAULT 'author',status VARCHAR(24) NOT NULL DEFAULT 'active',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS seo_settings (id INT PRIMARY KEY,site_title VARCHAR(255) NOT NULL,description TEXT NOT NULL,canonical_url TEXT NOT NULL,og_image TEXT NOT NULL,robots VARCHAR(64) NOT NULL DEFAULT 'index,follow',updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS analytics_daily (id INT AUTO_INCREMENT PRIMARY KEY,date VARCHAR(10) NOT NULL UNIQUE,views INT NOT NULL DEFAULT 0,visitors INT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS homepage_settings (id INT PRIMARY KEY,config LONGTEXT NOT NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190) NOT NULL UNIQUE,display_name VARCHAR(190) NOT NULL,password_hash VARCHAR(255) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'active',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS user_sessions (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,token_hash VARCHAR(64) NOT NULL UNIQUE,expires_at TIMESTAMP NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_user_sessions_user_id(user_id),CONSTRAINT fk_user_sessions_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);`;
try{
 await pool.query(sql);
 const has=async(table,column)=>{const[rows]=await pool.execute("SELECT COUNT(*) count FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?",[table,column]);return Number(rows[0].count)>0};
 if(!await has("users","role"))await pool.query("ALTER TABLE users ADD COLUMN role VARCHAR(32) NOT NULL DEFAULT 'member' AFTER password_hash, ADD INDEX idx_users_role(role)");
 if(!await has("posts","author_id"))await pool.query("ALTER TABLE posts ADD COLUMN author_id INT NULL AFTER category_id, ADD INDEX idx_posts_author_id(author_id), ADD CONSTRAINT fk_posts_author FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE SET NULL");
 await pool.execute("UPDATE users SET role='super_admin',status='active' WHERE email=?",["bilgincavus@gmail.com"]);
 console.log("Hostinger MySQL şeması hazır.")
}finally{await pool.end()}
