import mysql from "mysql2/promise";

const pool=mysql.createPool({uri:process.env.DATABASE_URL,host:process.env.DB_HOST,port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:process.env.DB_NAME,multipleStatements:true});
const sql=`
CREATE TABLE IF NOT EXISTS categories (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(160) NOT NULL,slug VARCHAR(160) NOT NULL UNIQUE,description TEXT NOT NULL,color VARCHAR(20) NOT NULL DEFAULT '#ee7551',sort_order INT NOT NULL DEFAULT 0,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_categories_sort_order(sort_order));
CREATE TABLE IF NOT EXISTS posts (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL,slug VARCHAR(190) NOT NULL UNIQUE,excerpt TEXT NOT NULL,content LONGTEXT NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'draft',category_id INT NULL,cover_url TEXT NOT NULL,cover_alt VARCHAR(255) NOT NULL,seo_title VARCHAR(255) NOT NULL,seo_description TEXT NOT NULL,published_at TIMESTAMP NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_posts_category_id(category_id),INDEX idx_posts_status_published_at(status,published_at),CONSTRAINT fk_posts_category FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS tags (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(160) NOT NULL,slug VARCHAR(160) NOT NULL UNIQUE,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS post_tags (post_id INT NOT NULL,tag_id INT NOT NULL,PRIMARY KEY(post_id,tag_id),INDEX idx_post_tags_tag_id(tag_id),FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE CASCADE,FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS media (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255) NOT NULL,\`key\` VARCHAR(255) NOT NULL UNIQUE,url TEXT NOT NULL,alt VARCHAR(255) NOT NULL,mime_type VARCHAR(120) NOT NULL,size BIGINT NOT NULL DEFAULT 0,content LONGBLOB NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS admin_users (id INT AUTO_INCREMENT PRIMARY KEY,user_id VARCHAR(190) NOT NULL UNIQUE,email VARCHAR(190) NOT NULL UNIQUE,display_name VARCHAR(190) NOT NULL,role VARCHAR(32) NOT NULL DEFAULT 'author',status VARCHAR(24) NOT NULL DEFAULT 'active',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS seo_settings (id INT PRIMARY KEY,site_title VARCHAR(255) NOT NULL,description TEXT NOT NULL,canonical_url TEXT NOT NULL,og_image TEXT NOT NULL,robots VARCHAR(64) NOT NULL DEFAULT 'index,follow',updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS analytics_daily (id INT AUTO_INCREMENT PRIMARY KEY,date VARCHAR(10) NOT NULL UNIQUE,views INT NOT NULL DEFAULT 0,visitors INT NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS analytics_events (id BIGINT AUTO_INCREMENT PRIMARY KEY,event_type VARCHAR(32) NOT NULL DEFAULT 'pageview',visitor_id VARCHAR(64) NOT NULL,session_id VARCHAR(64) NOT NULL,path VARCHAR(512) NOT NULL,referrer TEXT NOT NULL,channel VARCHAR(32) NOT NULL DEFAULT 'direct',device VARCHAR(24) NOT NULL DEFAULT 'desktop',country VARCHAR(80) NOT NULL DEFAULT 'Bilinmiyor',duration_seconds INT NOT NULL DEFAULT 0,post_id INT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_analytics_created(created_at),INDEX idx_analytics_path_created(path,created_at),INDEX idx_analytics_visitor_created(visitor_id,created_at),INDEX idx_analytics_post_created(post_id,created_at),CONSTRAINT fk_analytics_post FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS crm_leads (id INT AUTO_INCREMENT PRIMARY KEY,company VARCHAR(190) NOT NULL,contact_name VARCHAR(190) NOT NULL,email VARCHAR(190) NOT NULL,phone VARCHAR(50) NOT NULL,stage VARCHAR(32) NOT NULL DEFAULT 'new',source VARCHAR(50) NOT NULL DEFAULT 'website',owner VARCHAR(190) NOT NULL,country VARCHAR(80) NOT NULL,value INT NOT NULL DEFAULT 0,next_action VARCHAR(190) NOT NULL,next_action_at TIMESTAMP NULL,notes TEXT NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_crm_stage(stage),INDEX idx_crm_owner(owner),INDEX idx_crm_source(source),INDEX idx_crm_next_action(next_action_at));
CREATE TABLE IF NOT EXISTS crm_activities (id INT AUTO_INCREMENT PRIMARY KEY,lead_id INT NOT NULL,type VARCHAR(32) NOT NULL,description VARCHAR(255) NOT NULL,created_by VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_crm_activity_lead(lead_id),INDEX idx_crm_activity_created(created_at),CONSTRAINT fk_crm_activity_lead FOREIGN KEY(lead_id) REFERENCES crm_leads(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS homepage_settings (id INT PRIMARY KEY,config LONGTEXT NOT NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS system_settings (id INT PRIMARY KEY,config LONGTEXT NOT NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS framework_areas (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(190) NOT NULL,description TEXT NOT NULL,engine VARCHAR(64) NOT NULL,level INT NOT NULL DEFAULT 3,coverage INT NOT NULL DEFAULT 0,status VARCHAR(24) NOT NULL DEFAULT 'draft',content_need INT NOT NULL DEFAULT 0,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_framework_engine(engine),INDEX idx_framework_level(level),INDEX idx_framework_status(status));
CREATE TABLE IF NOT EXISTS content_opportunities (id INT AUTO_INCREMENT PRIMARY KEY,source_key VARCHAR(190) NOT NULL UNIQUE,title VARCHAR(255) NOT NULL,description TEXT NOT NULL,engine VARCHAR(64) NOT NULL,framework_area_id INT NULL,category_id INT NULL,content_type VARCHAR(50) NOT NULL DEFAULT 'article',priority VARCHAR(24) NOT NULL DEFAULT 'medium',focus_keyword VARCHAR(190) NOT NULL,suggested_publish_at TIMESTAMP NULL,status VARCHAR(24) NOT NULL DEFAULT 'suggested',post_id INT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_content_opportunity_status(status),INDEX idx_content_opportunity_engine(engine),INDEX idx_content_opportunity_priority(priority),FOREIGN KEY(framework_area_id) REFERENCES framework_areas(id) ON DELETE SET NULL,FOREIGN KEY(category_id) REFERENCES categories(id) ON DELETE SET NULL,FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS content_activities (id INT AUTO_INCREMENT PRIMARY KEY,post_id INT NULL,post_title VARCHAR(255) NOT NULL,action VARCHAR(32) NOT NULL,description VARCHAR(500) NOT NULL,actor_email VARCHAR(190) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_content_activity_post(post_id),INDEX idx_content_activity_created(created_at),INDEX idx_content_activity_action(action),FOREIGN KEY(post_id) REFERENCES posts(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190) NOT NULL UNIQUE,display_name VARCHAR(190) NOT NULL,password_hash VARCHAR(255) NOT NULL,status VARCHAR(24) NOT NULL DEFAULT 'active',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS user_invites (id INT AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190) NOT NULL,display_name VARCHAR(190) NOT NULL,role VARCHAR(32) NOT NULL,team VARCHAR(100) NOT NULL DEFAULT 'Genel',token_hash VARCHAR(64) NOT NULL UNIQUE,status VARCHAR(24) NOT NULL DEFAULT 'pending',invited_by VARCHAR(190) NOT NULL,expires_at TIMESTAMP NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_user_invite_email(email),INDEX idx_user_invite_status(status));
CREATE TABLE IF NOT EXISTS user_activities (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NULL,actor_email VARCHAR(190) NOT NULL,action VARCHAR(64) NOT NULL,description VARCHAR(255) NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_user_activity_created(created_at),INDEX idx_user_activity_user(user_id),CONSTRAINT fk_user_activity_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS user_sessions (id INT AUTO_INCREMENT PRIMARY KEY,user_id INT NOT NULL,token_hash VARCHAR(64) NOT NULL UNIQUE,expires_at TIMESTAMP NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX idx_user_sessions_user_id(user_id),CONSTRAINT fk_user_sessions_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);`;
const researchSql=`CREATE TABLE IF NOT EXISTS research_items (id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(255) NOT NULL,author VARCHAR(190) NOT NULL,type VARCHAR(50) NOT NULL DEFAULT 'Report',engine VARCHAR(80) NOT NULL DEFAULT 'Value Creation',source VARCHAR(190) NOT NULL,source_url TEXT NOT NULL,publication_year INT NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'review',favorite INT NOT NULL DEFAULT 0,citation_count INT NOT NULL DEFAULT 0,notes TEXT NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX idx_research_status(status),INDEX idx_research_engine(engine),INDEX idx_research_year(publication_year))`;
try{
 await pool.query(sql);
 await pool.query(researchSql);
 const has=async(table,column)=>{const[rows]=await pool.execute("SELECT COUNT(*) count FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?",[table,column]);return Number(rows[0].count)>0};
 if(!await has("users","role"))await pool.query("ALTER TABLE users ADD COLUMN role VARCHAR(32) NOT NULL DEFAULT 'member' AFTER password_hash, ADD INDEX idx_users_role(role)");
 if(!await has("users","team"))await pool.query("ALTER TABLE users ADD COLUMN team VARCHAR(100) NOT NULL DEFAULT 'Genel' AFTER role, ADD INDEX idx_users_team(team)");
 if(!await has("users","last_login_at"))await pool.query("ALTER TABLE users ADD COLUMN last_login_at TIMESTAMP NULL AFTER status");
 if(!await has("posts","author_id"))await pool.query("ALTER TABLE posts ADD COLUMN author_id INT NULL AFTER category_id, ADD INDEX idx_posts_author_id(author_id), ADD CONSTRAINT fk_posts_author FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE SET NULL");
 await pool.execute("UPDATE users SET role='super_admin',status='active' WHERE email=?",["bilgincavus@gmail.com"]);
 console.log("Hostinger MySQL şeması hazır.")
}finally{await pool.end()}
