"use client";
import {useEffect,useMemo,useState} from "react";
import {defaultHomeConfig,HomeConfig,HomeSection,normalizeHomeConfig} from "../../homepage-config";
import HeroCanvas from "./HeroCanvas";
type MediaItem={id:number;name:string;url:string;alt:string;mimeType:string};
type StudioTab="design"|"settings"|"seo"|"templates"|"history";
const blocks=["Hero","Öne Çıkan Alanlar","Hakkımızda","Value Engines","Programlar","İçerik Listesi","Araştırma","Video","CTA (Eylem Alanı)","Testimonial","Logo / Partner","İstatistik","Ekibimiz","Fiyatlandırma","SSS","Bülten Aboneliği","Alt Bilgi"];
const icons=["▣","⌘","♙","◉","▤","☷","⌕","▣","▱","◉","▧","⌁","♙","▥","?","✉","▤"];
const blankSection=(title="Yeni Bölüm"):HomeSection=>({id:`section-${Date.now()}`,type:"content",title,eyebrow:"YENİ BÖLÜM",body:"Bölüm açıklamasını buraya yazın.",visible:true,postIds:[],imageUrl:"",imageAlt:"",buttonLabel:"Detayları gör",buttonHref:"#"});
function SectionPreview({section}:{section:HomeSection}){return <section className="studio-preview-section">{section.imageUrl&&<img src={section.imageUrl} alt=""/>}<div><small>{section.eyebrow}</small><h3>{section.title}</h3><p>{section.body||"Bu bölümün içeriğini sağdaki ayarlardan düzenleyin."}</p>{section.buttonLabel&&<button>{section.buttonLabel} →</button>}</div></section>}
export default function HomeDesigner(){
 const[config,setConfig]=useState<HomeConfig>(defaultHomeConfig),[media,setMedia]=useState<MediaItem[]>([]),[ready,setReady]=useState(false),[message,setMessage]=useState(""),[tab,setTab]=useState<StudioTab>("design"),[mode,setMode]=useState<"home"|"pages">("home"),[selected,setSelected]=useState("hero"),[device,setDevice]=useState<"desktop"|"tablet"|"mobile">("desktop"),[library,setLibrary]=useState<"components"|"blocks">("components");
 useEffect(()=>{Promise.all([fetch("/api/admin/homepage").then(r=>r.json()),fetch("/api/admin/modules?module=media").then(r=>r.json())]).then(([home,items])=>{if(home.item)setConfig(normalizeHomeConfig(home.item));setMedia(items.items||[])}).finally(()=>setReady(true))},[]);
 const current=useMemo(()=>config.sections.find(x=>x.id===selected),[config.sections,selected]);
 const updateSection=(id:string,patch:Partial<HomeSection>)=>setConfig(v=>({...v,sections:v.sections.map(x=>x.id===id?{...x,...patch}:x)}));
 const add=(title:string)=>{const next=blankSection(title);setConfig(v=>({...v,sections:[...v.sections,next]}));setSelected(next.id)};
 const move=(index:number,delta:number)=>{const sections=[...config.sections],target=index+delta;if(target<0||target>=sections.length)return;[sections[index],sections[target]]=[sections[target],sections[index]];setConfig({...config,sections})};
 async function save(publish=false){const r=await fetch("/api/admin/homepage",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(config)});setMessage(r.ok?(publish?"Ana sayfa yayımlandı.":"Taslak kaydedildi."):"Değişiklikler kaydedilemedi.")}
 if(!ready)return <div className="page-studio loading">Tasarım stüdyosu hazırlanıyor…</div>;
 return <div className="page-studio"><header className="studio-header"><div><h1>{mode==="home"?"Ana Sayfa Tasarımı":"Sayfa Tasarımı"} <span>ⓘ</span></h1><p>Web Site <b>›</b> {mode==="home"?"Ana Sayfa":"Sayfalar"} <b>›</b> Düzenle</p></div><div className="studio-actions"><a href="/" target="_blank">◉ Önizleme</a><div className="devices"><button className={device==="desktop"?"active":""} onClick={()=>setDevice("desktop")}>▣</button><button className={device==="tablet"?"active":""} onClick={()=>setDevice("tablet")}>▯</button><button className={device==="mobile"?"active":""} onClick={()=>setDevice("mobile")}>▯</button></div><button onClick={()=>save(false)}>Taslağı Kaydet</button><button className="publish" onClick={()=>save(true)}>Yayınla⌄</button></div></header>
  {message&&<button className="studio-message" onClick={()=>setMessage("")}>{message} ×</button>}
  <nav className="studio-tabs"><button className={mode==="home"?"active":""} onClick={()=>setMode("home")}>Ana Sayfa</button><button className={mode==="pages"?"active":""} onClick={()=>setMode("pages")}>Sayfalar</button><i/>{(["design","settings","seo","templates","history"] as StudioTab[]).map((x,i)=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{["Tasarım","Ayarlar","SEO","Şablonlar","Geçmiş"][i]}</button>)}</nav>
  {mode==="pages"?<PageLibrary onEdit={()=>setMode("home")}/>:<div className="studio-grid">
   <aside className="component-library"><h2>BİLEŞENLER</h2><div className="mini-tabs"><button className={library==="components"?"active":""} onClick={()=>setLibrary("components")}>Bileşenler</button><button className={library==="blocks"?"active":""} onClick={()=>setLibrary("blocks")}>Bloklar</button></div><div className="block-list">{blocks.slice(0,library==="components"?17:10).map((x,i)=><button onClick={()=>x==="Hero"?setSelected("hero"):add(x)} key={x}><span>{icons[i]}</span>{x}<b>＋</b></button>)}</div></aside>
   <main className="studio-canvas-panel"><header><strong>⌂ ANA SAYFA YAPISI</strong><button>↻ Tüm Bölümleri Yönet</button></header><div className={`site-canvas ${device}`}>
    <div className="canvas-site-header"><b>OP8<sup>™</sup></b><nav>Framework · Programlar · Kaynaklar · Hakkımızda · İletişim</nav><button>Giriş</button></div>
    <button className={`canvas-section-button ${selected==="hero"?"canvas-selected":""}`} onClick={()=>setSelected("hero")}><HeroCanvas config={config} onChange={layout=>setConfig({...config,hero:{...config.hero,layout}})}/></button>
    <section className="engine-strip"><h2>8 Value Engines. Infinite Impact.</h2><p>OP8, işletmenizin tüm kritik alanlarında değer yaratmanızı sağlayan 8 entegre Value Engine üzerinden çalışır.</p><div>{["Strategy","Growth","Operational Excellence","People","Technology","Capital","Governance","Sustainability"].map((x,i)=><article key={x}><i>{icons[i]}</i><b>{x}<br/>Engine</b></article>)}</div></section>
    {config.sections.filter(x=>x.visible).map(x=><button className={`canvas-section-button ${selected===x.id?"canvas-selected":""}`} onClick={()=>setSelected(x.id)} key={x.id}><SectionPreview section={x}/></button>)}
   </div></main>
   <aside className="studio-inspector"><Structure config={config} selected={selected} setSelected={setSelected} move={move} update={updateSection}/>{tab==="design"?<Editor config={config} setConfig={setConfig} selected={selected} section={current} update={updateSection} media={media}/>:<TabPanel tab={tab}/>}</aside>
  </div>}
 </div>
}
function Structure({config,selected,setSelected,move,update}:{config:HomeConfig;selected:string;setSelected:(x:string)=>void;move:(i:number,d:number)=>void;update:(id:string,p:Partial<HomeSection>)=>void}){const rows=[{id:"header",title:"Header"},{id:"hero",title:"Hero"},...config.sections.map(x=>({id:x.id,title:x.title}))];return <section className="structure"><h2>BÖLÜM YAPISI</h2>{rows.map((row,i)=><div className={selected===row.id?"structure-row active":"structure-row"} key={row.id}><button onClick={()=>setSelected(row.id)}><span>▣</span><b>{row.title}</b></button>{i>1&&<><button aria-label="Görünürlüğü değiştir" onClick={()=>update(row.id,{visible:!config.sections[i-2].visible})}>{config.sections[i-2].visible?"◉":"○"}</button><button aria-label="Yukarı taşı" onClick={()=>move(i-2,-1)}>↕</button></>}</div>)}</section>}
function Editor({config,setConfig,selected,section,update,media}:{config:HomeConfig;setConfig:(v:HomeConfig)=>void;selected:string;section?:HomeSection;update:(id:string,p:Partial<HomeSection>)=>void;media:MediaItem[]}){if(selected==="header")return <section className="section-settings"><h2>HEADER AYARLARI</h2><label>Site adı<input value={config.brand.siteName} onChange={e=>setConfig({...config,brand:{...config.brand,siteName:e.target.value}})}/></label><label>Logo URL<input value={config.brand.logoUrl} onChange={e=>setConfig({...config,brand:{...config.brand,logoUrl:e.target.value}})}/></label></section>;if(selected==="hero")return <section className="section-settings"><h2>HERO AYARLARI</h2>{[["Üst başlık","eyebrow"],["Ana başlık","title"],["Vurgulu satır","accent"],["Açıklama","description"]].map(([label,key])=><label key={key}>{label}<textarea value={String(config.hero[key as keyof typeof config.hero])} onChange={e=>setConfig({...config,hero:{...config.hero,[key]:e.target.value}})}/></label>)}<label>Hero görseli<select value={config.hero.imageUrl} onChange={e=>setConfig({...config,hero:{...config.hero,imageUrl:e.target.value}})}><option value="">Görsel seçin</option>{media.filter(x=>x.mimeType.startsWith("image/")).map(x=><option value={x.url} key={x.id}>{x.name}</option>)}</select></label><label>Arka plan<input type="color" value={config.theme.ink} onChange={e=>setConfig({...config,theme:{...config.theme,ink:e.target.value}})}/></label></section>;if(!section)return <section className="section-settings"><h2>BÖLÜM AYARLARI</h2><p>Düzenlemek için tuvalden veya bölüm yapısından bir alan seçin.</p></section>;return <section className="section-settings"><h2>BÖLÜM AYARLARI</h2><label>Başlık<input value={section.title} onChange={e=>update(section.id,{title:e.target.value})}/></label><label>Üst başlık<input value={section.eyebrow} onChange={e=>update(section.id,{eyebrow:e.target.value})}/></label><label>Açıklama<textarea rows={4} value={section.body} onChange={e=>update(section.id,{body:e.target.value})}/></label><label>Görsel<select value={section.imageUrl} onChange={e=>update(section.id,{imageUrl:e.target.value})}><option value="">Görsel seçin</option>{media.filter(x=>x.mimeType.startsWith("image/")).map(x=><option value={x.url} key={x.id}>{x.name}</option>)}</select></label><label>İçerik genişliği<select><option>Geniş</option><option>Standart</option><option>Dar</option></select></label><label className="toggle">Bu bölümü göster<input type="checkbox" checked={section.visible} onChange={e=>update(section.id,{visible:e.target.checked})}/></label></section>}
function TabPanel({tab}:{tab:StudioTab}){const content={settings:["Sayfa genişliği","Arka plan","Animasyonlar","Global boşluklar"],seo:["SEO başlığı","Meta açıklama","Canonical URL","Sosyal paylaşım görseli"],templates:["Kurumsal Ana Sayfa","İçerik Merkezi","Program Tanıtımı","Boş Şablon"],history:["Son yayımlanan sürüm","Bugünkü taslak","Önceki sürümler","Geri yükleme"]};return <section className="section-settings"><h2>{tab.toLocaleUpperCase("tr-TR")}</h2>{content[tab as keyof typeof content]?.map(x=><button className="setting-row" key={x}>{x}<span>›</span></button>)}</section>}
function PageLibrary({onEdit}:{onEdit:()=>void}){return <section className="page-library"><header><div><h2>Sayfalar</h2><p>Sabit sayfaları oluşturun, tasarlayın ve yayın durumlarını yönetin.</p></div><button>＋ Yeni Sayfa</button></header><div className="page-cards">{["Ana Sayfa","OP8 Framework","Programlar","Hakkımızda","İletişim","Kaynaklar"].map((x,i)=><article key={x}><i>{icons[i]}</i><div><h3>{x}</h3><p>/{i?x.toLocaleLowerCase("tr-TR").replaceAll(" ","-"):""}</p></div><span>{i<4?"Yayında":"Taslak"}</span><button onClick={onEdit}>Düzenle</button></article>)}</div></section>}
