"use client";
import {useEffect,useState} from "react";
import {defaultHomeConfig,HeroTextStyle,HomeConfig,HomeSection,normalizeHomeConfig} from "../../homepage-config";
import HeroCanvas from "./HeroCanvas";
type MediaItem={id:number;name:string;url:string;alt:string;mimeType:string};
const fonts=["Arial, Helvetica, sans-serif","Georgia, 'Times New Roman', serif","Verdana, Geneva, sans-serif","Tahoma, Geneva, sans-serif","Trebuchet MS, Arial, sans-serif","'Times New Roman', Times, serif"];
const blankSection=():HomeSection=>({id:`section-${Date.now()}`,type:"content",title:"Yeni bölüm",eyebrow:"YENİ BÖLÜM",body:"Bölüm açıklamasını buraya yazın.",visible:true,postIds:[],imageUrl:"",imageAlt:"",buttonLabel:"Detayları gör",buttonHref:"#"});

function Typography({label,value,onChange}:{label:string;value:HeroTextStyle;onChange:(value:HeroTextStyle)=>void}){return <fieldset className="type-controls"><legend>{label} biçimi</legend><div className="type-grid"><label>Yazı karakteri<select value={value.fontFamily} onChange={e=>onChange({...value,fontFamily:e.target.value})}>{fonts.map(font=><option value={font} key={font} style={{fontFamily:font}}>{font.split(",")[0].replaceAll("'","")}</option>)}</select></label><label>Punto (px)<input type="number" min="8" max="160" value={value.fontSize} onChange={e=>onChange({...value,fontSize:Number(e.target.value)||8})}/></label><label>Yazı rengi<div className="color-field"><input type="color" value={value.color} onChange={e=>onChange({...value,color:e.target.value})}/><input value={value.color} pattern="#[0-9a-fA-F]{6}" onChange={e=>onChange({...value,color:e.target.value})}/></div></label></div></fieldset>}
function MediaPicker({items,value,onSelect}:{items:MediaItem[];value:string;onSelect:(item:MediaItem)=>void}){const images=items.filter(item=>item.mimeType.startsWith("image/"));return <div className="media-picker"><div className="media-picker-head"><strong>Medya kütüphanesinden seç</strong><span>{images.length} görsel</span></div>{images.length===0?<p>Henüz görsel yüklenmemiş. Önce Medya bölümünden bir görsel ekleyin.</p>:<div className="media-picker-grid">{images.map(item=><button type="button" className={value===item.url?"selected":""} onClick={()=>onSelect(item)} key={item.id} title={item.name}><img src={item.url} alt={item.alt||item.name}/><span>{item.name}</span></button>)}</div>}</div>}

export default function HomeDesigner(){
 const[config,setConfig]=useState<HomeConfig>(defaultHomeConfig),[media,setMedia]=useState<MediaItem[]>([]),[message,setMessage]=useState("");
 useEffect(()=>{Promise.all([fetch("/api/admin/homepage").then(r=>r.json()),fetch("/api/admin/modules?module=media").then(r=>r.json())]).then(([home,library])=>{if(home.item)setConfig(normalizeHomeConfig(home.item));setMedia(library.items||[])})},[]);
 const hero=(key:keyof HomeConfig["hero"],value:string|HeroTextStyle)=>setConfig({...config,hero:{...config.hero,[key]:value}});
 const update=(id:string,key:keyof HomeSection,value:unknown)=>setConfig({...config,sections:config.sections.map(section=>section.id===id?{...section,[key]:value}:section)});
 const selectHero=(item:MediaItem)=>setConfig({...config,hero:{...config.hero,imageUrl:item.url,imageAlt:item.alt||item.name}});
 const selectSection=(id:string,item:MediaItem)=>setConfig({...config,sections:config.sections.map(section=>section.id===id?{...section,imageUrl:item.url,imageAlt:item.alt||item.name}:section)});
 const move=(index:number,direction:number)=>{const next=[...config.sections],target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setConfig({...config,sections:next})};
 async function save(){const response=await fetch("/api/admin/homepage",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(config)});setMessage(response.ok?"Ana sayfa tasarımı kaydedildi.":"Kaydedilemedi.")}
 return <div className="home-designer"><div className="admin-title"><div><p className="eyebrow">GÖRSEL YÖNETİM</p><h1>Ana Sayfa Tasarımı</h1><p>Hero alanını ve sayfa bölümlerini düzenle.</p></div><button className="admin-primary top" onClick={save}>Değişiklikleri yayımla</button></div>{message&&<p className="admin-message">{message}</p>}<div className="designer-grid">
 <section className="designer-panel"><h2>Hero alanı</h2>
  <label>Üst başlık<input value={config.hero.eyebrow} onChange={e=>hero("eyebrow",e.target.value)}/></label><Typography label="Üst başlık" value={config.hero.eyebrowStyle} onChange={v=>hero("eyebrowStyle",v)}/>
  <label>Ana başlık<input value={config.hero.title} onChange={e=>hero("title",e.target.value)}/></label><Typography label="Ana başlık" value={config.hero.titleStyle} onChange={v=>hero("titleStyle",v)}/>
  <label>Vurgulu satır<input value={config.hero.accent} onChange={e=>hero("accent",e.target.value)}/></label><Typography label="Vurgulu satır" value={config.hero.accentStyle} onChange={v=>hero("accentStyle",v)}/>
  <label>Açıklama<textarea rows={4} value={config.hero.description} onChange={e=>hero("description",e.target.value)}/></label><Typography label="Açıklama" value={config.hero.descriptionStyle} onChange={v=>hero("descriptionStyle",v)}/>
  <div className="field-pair"><label>Buton metni<input value={config.hero.buttonLabel} onChange={e=>hero("buttonLabel",e.target.value)}/></label><label>Buton bağlantısı<input value={config.hero.buttonHref} onChange={e=>hero("buttonHref",e.target.value)}/></label></div><label>Hero görseli URL<input value={config.hero.imageUrl} onChange={e=>hero("imageUrl",e.target.value)} placeholder="Medya URL’si veya dış görsel adresi"/></label><MediaPicker items={media} value={config.hero.imageUrl} onSelect={selectHero}/><label>Görsel alt metni<input value={config.hero.imageAlt} onChange={e=>hero("imageAlt",e.target.value)}/></label>
 </section>
 <section className="designer-panel"><div className="panel-head"><div><p className="kicker">SAYFA AKIŞI</p><h2>Bölümler</h2></div><button className="add-section" onClick={()=>setConfig({...config,sections:[...config.sections,blankSection()]})}>+ Yeni bölüm</button></div>{config.sections.map((section,index)=><article className="section-editor expanded" key={section.id}><div className="section-order"><button disabled={index===0} onClick={()=>move(index,-1)}>↑</button><button disabled={index===config.sections.length-1} onClick={()=>move(index,1)}>↓</button></div><div><div className="section-title-row"><select value={section.type} onChange={e=>update(section.id,"type",e.target.value)}><option value="content">Görselli içerik</option><option value="featured">Öne çıkan yazı</option><option value="latest">Yazı listesi</option><option value="topics">Konular</option><option value="newsletter">Bülten</option></select><button className="remove-section" onClick={()=>confirm("Bu bölüm silinsin mi?")&&setConfig({...config,sections:config.sections.filter(x=>x.id!==section.id)})}>Sil</button></div><label>Başlık<input value={section.title} onChange={e=>update(section.id,"title",e.target.value)}/></label><label>Üst başlık<input value={section.eyebrow} onChange={e=>update(section.id,"eyebrow",e.target.value)}/></label><label>Açıklama<textarea rows={3} value={section.body} onChange={e=>update(section.id,"body",e.target.value)}/></label><label>Görsel URL<input value={section.imageUrl} onChange={e=>update(section.id,"imageUrl",e.target.value)}/></label><MediaPicker items={media} value={section.imageUrl} onSelect={item=>selectSection(section.id,item)}/><label>Görsel alt metni<input value={section.imageAlt} onChange={e=>update(section.id,"imageAlt",e.target.value)}/></label></div><label className="visibility"><input type="checkbox" checked={section.visible} onChange={e=>update(section.id,"visible",e.target.checked)}/> Göster</label></article>)}</section>
 <aside className="home-preview"><p className="kicker">CANLI ÖN İZLEME</p><div className="preview-hero">{config.hero.imageUrl&&<img src={config.hero.imageUrl} alt=""/>}<small style={config.hero.eyebrowStyle}>{config.hero.eyebrow}</small><h2><span style={config.hero.titleStyle}>{config.hero.title}</span><em style={config.hero.accentStyle}>{config.hero.accent}</em></h2><p style={config.hero.descriptionStyle}>{config.hero.description}</p><span>{config.hero.buttonLabel} →</span></div>{config.sections.filter(x=>x.visible).map(section=><div className="preview-section" key={section.id}>{section.imageUrl&&<img src={section.imageUrl} alt=""/>}<small>{section.eyebrow}</small><strong>{section.title}</strong></div>)}</aside>
 </div></div>
}
