"use client";

import { useEffect, useState } from "react";
import { defaultHomeConfig, HomeConfig, HomeSection, normalizeHomeConfig } from "../../homepage-config";

type MediaItem={id:number;name:string;url:string;alt:string;mimeType:string};
const blankSection=():HomeSection=>({id:`section-${Date.now()}`,type:"content",title:"Yeni bölüm",eyebrow:"YENİ BÖLÜM",body:"Bölüm açıklamasını buraya yazın.",visible:true,postIds:[],imageUrl:"",imageAlt:"",buttonLabel:"Detayları gör",buttonHref:"#"});

function MediaPicker({items,value,onSelect}:{items:MediaItem[];value:string;onSelect:(item:MediaItem)=>void}){
  const images=items.filter(item=>item.mimeType.startsWith("image/"));
  return <div className="media-picker">
    <div className="media-picker-head"><strong>Medya kütüphanesinden seç</strong><span>{images.length} görsel</span></div>
    {images.length===0?<p>Henüz görsel yüklenmemiş. Önce Medya bölümünden bir görsel ekleyin.</p>:<div className="media-picker-grid">{images.map(item=><button type="button" className={value===item.url?"selected":""} onClick={()=>onSelect(item)} key={item.id} title={item.name}><img src={item.url} alt={item.alt||item.name}/><span>{item.name}</span></button>)}</div>}
  </div>
}

export default function HomeDesigner(){
  const[config,setConfig]=useState<HomeConfig>(defaultHomeConfig),[media,setMedia]=useState<MediaItem[]>([]),[message,setMessage]=useState("");
  useEffect(()=>{Promise.all([fetch("/api/admin/homepage").then(r=>r.json()),fetch("/api/admin/modules?module=media").then(r=>r.json())]).then(([home,library])=>{if(home.item)setConfig(normalizeHomeConfig(home.item));setMedia(library.items||[])})},[]);
  const hero=(key:keyof HomeConfig["hero"],value:string)=>setConfig({...config,hero:{...config.hero,[key]:value}});
  const update=(id:string,key:keyof HomeSection,value:unknown)=>setConfig({...config,sections:config.sections.map(section=>section.id===id?{...section,[key]:value}:section)});
  const selectHero=(item:MediaItem)=>setConfig({...config,hero:{...config.hero,imageUrl:item.url,imageAlt:item.alt||item.name}});
  const selectSection=(id:string,item:MediaItem)=>setConfig({...config,sections:config.sections.map(section=>section.id===id?{...section,imageUrl:item.url,imageAlt:item.alt||item.name}:section)});
  const move=(index:number,direction:number)=>{const next=[...config.sections],target=index+direction;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setConfig({...config,sections:next})};
  const add=()=>setConfig({...config,sections:[...config.sections,blankSection()]});
  const remove=(id:string)=>confirm("Bu bölüm silinsin mi?")&&setConfig({...config,sections:config.sections.filter(section=>section.id!==id)});
  async function save(){const response=await fetch("/api/admin/homepage",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(config)});setMessage(response.ok?"Ana sayfa tasarımı yayımlandı.":"Kaydedilemedi.")}

  return <div className="home-designer"><div className="admin-title"><div><p className="eyebrow">GÖRSEL YÖNETİM</p><h1>Ana Sayfa Tasarımı</h1><p>Hero alanını ve sayfa bölümlerini düzenle.</p></div><button className="admin-primary top" onClick={save}>Değişiklikleri yayımla</button></div>{message&&<p className="admin-message">{message}</p>}<div className="designer-grid">
    <section className="designer-panel"><h2>Hero alanı</h2><label>Üst başlık<input value={config.hero.eyebrow} onChange={e=>hero("eyebrow",e.target.value)}/></label><label>Ana başlık<input value={config.hero.title} onChange={e=>hero("title",e.target.value)}/></label><label>Vurgulu satır<input value={config.hero.accent} onChange={e=>hero("accent",e.target.value)}/></label><label>Açıklama<textarea rows={4} value={config.hero.description} onChange={e=>hero("description",e.target.value)}/></label><div className="field-pair"><label>Buton metni<input value={config.hero.buttonLabel} onChange={e=>hero("buttonLabel",e.target.value)}/></label><label>Buton bağlantısı<input value={config.hero.buttonHref} onChange={e=>hero("buttonHref",e.target.value)}/></label></div><label>Hero görseli URL<input value={config.hero.imageUrl} onChange={e=>hero("imageUrl",e.target.value)} placeholder="Medya URL’si veya dış görsel adresi"/></label><MediaPicker items={media} value={config.hero.imageUrl} onSelect={selectHero}/><label>Görsel alt metni<input value={config.hero.imageAlt} onChange={e=>hero("imageAlt",e.target.value)}/></label></section>
    <section className="designer-panel"><div className="panel-head"><div><p className="kicker">SAYFA AKIŞI</p><h2>Bölümler</h2></div><button className="add-section" onClick={add}>+ Yeni bölüm</button></div>{config.sections.map((section,index)=><article className="section-editor expanded" key={section.id}><div className="section-order"><button disabled={index===0} onClick={()=>move(index,-1)}>↑</button><button disabled={index===config.sections.length-1} onClick={()=>move(index,1)}>↓</button></div><div><div className="section-title-row"><select value={section.type} onChange={e=>update(section.id,"type",e.target.value)}><option value="content">Görselli içerik</option><option value="featured">Öne çıkan yazı</option><option value="latest">Yazı listesi</option><option value="topics">Konular</option><option value="newsletter">Bülten</option></select><button className="remove-section" onClick={()=>remove(section.id)}>Sil</button></div><label>Başlık<input value={section.title} onChange={e=>update(section.id,"title",e.target.value)}/></label><label>Üst başlık<input value={section.eyebrow} onChange={e=>update(section.id,"eyebrow",e.target.value)}/></label><label>Açıklama<textarea rows={3} value={section.body} onChange={e=>update(section.id,"body",e.target.value)}/></label><label>Görsel URL<input value={section.imageUrl} onChange={e=>update(section.id,"imageUrl",e.target.value)} placeholder="Medya URL’si veya dış görsel adresi"/></label><MediaPicker items={media} value={section.imageUrl} onSelect={item=>selectSection(section.id,item)}/><label>Görsel alt metni<input value={section.imageAlt} onChange={e=>update(section.id,"imageAlt",e.target.value)}/></label><div className="field-pair"><label>Buton metni<input value={section.buttonLabel} onChange={e=>update(section.id,"buttonLabel",e.target.value)}/></label><label>Buton bağlantısı<input value={section.buttonHref} onChange={e=>update(section.id,"buttonHref",e.target.value)}/></label></div>{["featured","latest"].includes(section.type)&&<label>Yazı kimlikleri<input value={section.postIds.join(", ")} onChange={e=>update(section.id,"postIds",e.target.value.split(",").map(Number).filter(Boolean))}/></label>}</div><label className="visibility"><input type="checkbox" checked={section.visible} onChange={e=>update(section.id,"visible",e.target.checked)}/> Göster</label></article>)}</section>
    <aside className="home-preview"><p className="kicker">CANLI ÖN İZLEME</p><div className="preview-hero">{config.hero.imageUrl&&<img src={config.hero.imageUrl} alt=""/>}<small>{config.hero.eyebrow}</small><h2>{config.hero.title}<em>{config.hero.accent}</em></h2><p>{config.hero.description}</p><span>{config.hero.buttonLabel} →</span></div>{config.sections.filter(section=>section.visible).map(section=><div className="preview-section" key={section.id}>{section.imageUrl&&<img src={section.imageUrl} alt=""/>}<small>{section.eyebrow}</small><strong>{section.title}</strong><span>{section.buttonLabel||`${section.postIds.length} yazı seçili`}</span></div>)}</aside>
  </div></div>
}